{
  "hash": "619d53bb3bafcbfcf24679c2f23c3ff6",
  "result": {
    "engine": "knitr",
    "markdown": "---\nengine: knitr\nfilters:\n  - webr\nwebr:\n  show-startup-message: true\n  cell-options:\n    autorun: true\n---\n\n# Quality Management Systems\n\n---------------------\n\n## Learning Objectives\n\nAfter completing this chapter, you will be able to:\n\n1. Define quality management systems and explain their purpose in manufacturing\n2. Describe the structure and requirements of ISO 9001:2015\n3. Identify industry-specific quality standards (IATF 16949, AS9100, ISO 22000)\n4. Explain the documentation hierarchy and control requirements\n5. Conduct internal audits using systematic methodologies\n6. Implement effective corrective and preventive action (CAPA) processes\n7. Understand management review and continuous improvement requirements\n8. Integrate quality tools (SPC, PFMEA, MSA) within a QMS framework\n\n---\n\n## Introduction to Quality Management Systems\n\nA **Quality Management System (QMS)** is a formalized system that documents processes, procedures, and responsibilities for achieving quality policies and objectives. It coordinates and directs an organization's activities to meet customer and regulatory requirements while continuously improving effectiveness.\n\n### Why Implement a QMS?\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/qms-benefits-1.pdf)\n:::\n:::\n\n\n### The Evolution of Quality Management\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}llll}\n\\caption{\\label{tab:quality-evolution}Evolution of Quality Management}\\\\\n\\toprule\nEra & Approach & Focus & Key Figures/Standards\\\\\n\\midrule\n\\textbf{Pre-1900s} & Craftsmanship & Individual skill; master craftsmen & Guilds\\\\\n\\textbf{1900-1940s} & Inspection & Sort good from bad; end-of-line inspection & Taylor\\\\\n\\textbf{1940-1960s} & Statistical Quality Control & Control charts; sampling; Shewhart, Deming & Shewhart, Deming\\\\\n\\textbf{1960-1980s} & Quality Assurance & Prevention; systems approach; documented procedures & Juran, Feigenbaum\\\\\n\\textbf{1980-2000s} & Total Quality Management & Company-wide quality; customer focus; continuous improvement & Crosby, ISO 9000\\\\\n\\addlinespace\n\\cellcolor[HTML]{d5f5e3}{\\textbf{2000s-Present}} & \\cellcolor[HTML]{d5f5e3}{Integrated Management} & \\cellcolor[HTML]{d5f5e3}{Risk-based thinking; integration with business strategy; digital quality} & \\cellcolor[HTML]{d5f5e3}{ISO 9001:2015, Industry 4.0}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Quality Management Principles\n\nISO 9000 defines seven quality management principles that form the foundation of all QMS standards:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/qm-principles-1.pdf)\n:::\n:::\n\n\n---\n\n## ISO 9001:2015 Structure\n\n**ISO 9001:2015** is the international standard for quality management systems. It uses the High-Level Structure (HLS) common to all ISO management system standards.\n\n### The Ten Clauses\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/iso-clauses-1.pdf)\n:::\n:::\n\n\n### The Process Approach and PDCA\n\nISO 9001:2015 emphasizes the **process approach** combined with the **Plan-Do-Check-Act (PDCA)** cycle:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\ni Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/pdca-cycle-1.pdf)\n:::\n:::\n\n\n### Risk-Based Thinking\n\nISO 9001:2015 introduced **risk-based thinking** throughout the QMS:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}l>{}ll}\n\\caption{\\label{tab:risk-based}Risk-Based Thinking in ISO 9001:2015}\\\\\n\\toprule\nClause & Requirement & Risk\\_Application\\\\\n\\midrule\n\\textbf{4.1} & Context of the Organization & Identify internal/external issues that could affect QMS outcomes\\\\\n\\textbf{4.2} & Interested Parties & Understand needs/expectations that could impact quality\\\\\n\\textbf{6.1} & Actions to Address Risks and Opportunities & Plan actions to address risks and opportunities; integrate into processes\\\\\n\\textbf{8.1} & Operational Planning and Control & Control processes considering risks identified in planning\\\\\n\\textbf{9.1} & Monitoring and Measurement & Monitor effectiveness of actions taken to address risks\\\\\n\\addlinespace\n\\textbf{10.2} & Nonconformity and Corrective Action & Analyze nonconformities; update risks/opportunities as needed\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n<details><summary>**Understanding Risk-Based Thinking**</summary>\n\n**Risk-based thinking** doesn't require formal risk management (like FMEA for every process), but rather:\n\n1. **Consider risks** when designing and implementing the QMS\n2. **Preventive action** is built into the system, not a separate activity\n3. **Proportional response** - more rigorous controls for higher-risk processes\n4. **Opportunities** are also considered (not just negative risks)\n\n**Example:** A food manufacturer identifies \"allergen cross-contamination\" as a significant risk. Risk-based thinking leads them to:\n- Dedicated production lines for allergen-containing products\n- Enhanced cleaning verification procedures\n- Staff training on allergen awareness\n- Increased inspection frequency after changeovers\n\nThe extent of controls is proportional to the risk level.\n</details>\n\n---\n\n## Industry-Specific Quality Standards\n\nDifferent industries have developed standards that build upon ISO 9001 with additional sector-specific requirements.\n\n### Comparison of Major Standards\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/standards-comparison-1.pdf)\n:::\n:::\n\n\n### IATF 16949:2016 (Automotive)\n\n**IATF 16949** is the automotive quality standard, required by most major OEMs (Ford, GM, Toyota, VW, etc.).\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}l>{}l>{}l}\n\\caption{\\label{tab:iatf-additions}IATF 16949 Additional Requirements Beyond ISO 9001}\\\\\n\\toprule\nRequirement Area & ISO 9001 & IATF 16949 Addition\\\\\n\\midrule\n\\textbf{Product Safety} & \\cellcolor[HTML]{fadbd8}{Implied} & \\cellcolor[HTML]{d5f5e3}{Explicit requirements for product safety processes}\\\\\n\\textbf{APQP/PPAP} & \\cellcolor[HTML]{fadbd8}{Not specified} & \\cellcolor[HTML]{d5f5e3}{APQP phases required; PPAP submission mandatory}\\\\\n\\textbf{Control Plans} & \\cellcolor[HTML]{fadbd8}{Not specified} & \\cellcolor[HTML]{d5f5e3}{Control plans required for all parts; specific format}\\\\\n\\textbf{MSA} & \\cellcolor[HTML]{fadbd8}{General requirement} & \\cellcolor[HTML]{d5f5e3}{MSA studies required per AIAG MSA manual}\\\\\n\\textbf{SPC} & \\cellcolor[HTML]{fadbd8}{General requirement} & \\cellcolor[HTML]{d5f5e3}{SPC for all special characteristics}\\\\\n\\addlinespace\n\\textbf{Supplier Quality} & \\cellcolor[HTML]{fadbd8}{Basic purchasing} & \\cellcolor[HTML]{d5f5e3}{Supplier development; second-party audits; IATF certification flow-down}\\\\\n\\textbf{Warranty Management} & \\cellcolor[HTML]{fadbd8}{Complaint handling} & \\cellcolor[HTML]{d5f5e3}{NTF analysis; warranty data analysis; field return analysis}\\\\\n\\textbf{Manufacturing Feasibility} & \\cellcolor[HTML]{fadbd8}{Review of requirements} & \\cellcolor[HTML]{d5f5e3}{Documented manufacturing feasibility review}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Automotive Core Tools\n\nIATF 16949 requires the use of **five core tools**:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/core-tools-1.pdf)\n:::\n:::\n\n\n#### APQP: Advanced Product Quality Planning\n\n**APQP** is a structured framework for developing products that ensures customer requirements are met through careful planning and defined milestones.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_segment(aes(x = 0.6, xend = 5.4, y = 1, yend = 1), arrow = arrow(length = unit(0.3, : All aesthetics have length 1, but the data has 5 rows.\ni Please consider using `annotate()` or provide this layer with data containing\n  a single row.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/apqp-phases-1.pdf)\n:::\n:::\n\n\n::: {.example-box}\n**Example: New Brake Caliper Development**\n\nA Tier 1 supplier developing a new brake caliper for an OEM would follow APQP:\n\n- **Phase 1**: Gather customer requirements (stopping distance, weight limits, environmental conditions), benchmark competitor products\n- **Phase 2**: Design the caliper, create Design FMEA (what if piston seal fails?), build prototypes for testing\n- **Phase 3**: Design manufacturing process, create Process FMEA, develop control plan for machining and assembly\n- **Phase 4**: Run production trial, validate Cpk > 1.67 for critical dimensions, submit PPAP package\n- **Phase 5**: Monitor warranty returns, implement kaizen improvements, document lessons for next program\n:::\n\n#### PPAP: Production Part Approval Process\n\n**PPAP** provides evidence that the supplier understands customer requirements and can consistently produce conforming parts during actual production runs.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}ll}\n\\caption{\\label{tab:ppap-elements}PPAP 18 Elements Required for Submission}\\\\\n\\toprule\nElement & Description\\\\\n\\midrule\n\\textbf{1. Design Records} & Part drawings, CAD files, specifications\\\\\n\\textbf{2. Engineering Change Documents} & Documentation of any design changes since original approval\\\\\n\\textbf{3. Customer Engineering Approval} & Evidence of customer sign-off on design\\\\\n\\textbf{4. Design FMEA} & Risk analysis of product design failure modes\\\\\n\\textbf{5. Process Flow Diagram} & Visual representation of manufacturing steps\\\\\n\\addlinespace\n\\textbf{6. Process FMEA} & Risk analysis of process failure modes\\\\\n\\textbf{7. Control Plan} & Document describing controls for each process step\\\\\n\\textbf{8. MSA Studies} & Gage R\\&R studies proving measurement system adequacy\\\\\n\\textbf{9. Dimensional Results} & Actual measurements vs. specifications for all dimensions\\\\\n\\textbf{10. Material/Performance Test Results} & Test results for material properties and performance requirements\\\\\n\\addlinespace\n\\textbf{11. Initial Process Studies (SPC)} & Cpk/Ppk studies demonstrating process capability\\\\\n\\textbf{12. Qualified Lab Documentation} & Scope and accreditation of testing laboratories\\\\\n\\textbf{13. Appearance Approval Report} & Required for parts with color, grain, or surface requirements\\\\\n\\textbf{14. Sample Production Parts} & Parts from production run for customer evaluation\\\\\n\\textbf{15. Master Sample} & Retained reference sample for future comparison\\\\\n\\addlinespace\n\\textbf{16. Checking Aids} & Fixtures, gages, or templates used to inspect parts\\\\\n\\textbf{17. Customer-Specific Requirements} & OEM-specific requirements (Ford, GM, Toyota, etc.)\\\\\n\\textbf{18. Part Submission Warrant (PSW)} & Summary document with supplier certification\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n**PPAP Submission Levels:**\n\n| Level | Requirements | When Used |\n|:------|:-------------|:----------|\n| 1 | PSW only | Low-risk parts, trusted suppliers |\n| 2 | PSW + samples + limited data | Standard submission |\n| 3 | PSW + samples + complete data | Default level; new parts/suppliers |\n| 4 | PSW + other per customer direction | Customer-specified requirements |\n| 5 | PSW + samples + complete data at supplier site | Full documentation review on-site |\n\n::: {.example-box}\n**Example: Fuel Injector PPAP Submission**\n\nA supplier submitting PPAP for a new fuel injector would include:\n\n- **Dimensional results**: 100% inspection of 300 parts showing all 47 dimensions in spec\n- **MSA study**: Gage R&R < 10% for critical spray angle measurement\n- **Process capability**: Cpk = 1.89 for nozzle hole diameter (spec requires Cpk ≥ 1.67)\n- **Material certs**: Steel chemistry and hardness test results\n- **Performance tests**: Flow rate, spray pattern, durability (1 million cycles)\n- **PSW**: Signed warrant certifying all requirements met\n:::\n\n#### FMEA: Failure Mode and Effects Analysis\n\n**FMEA** is a systematic method for identifying potential failures, their causes, and effects, then prioritizing actions to reduce risk. Two types are used in automotive:\n\n- **Design FMEA (DFMEA)**: Analyzes potential failures in product design\n- **Process FMEA (PFMEA)**: Analyzes potential failures in manufacturing processes\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}ll>{}l}\n\\caption{\\label{tab:fmea-structure}Process FMEA Structure and Example}\\\\\n\\toprule\nColumn & Description & Example\\\\\n\\midrule\n\\textbf{Process Step} & The operation being analyzed & Torque fastener to 25 Nm\\\\\n\\textbf{Potential Failure Mode} & How the process could fail to meet requirements & Under-torque / Over-torque\\\\\n\\textbf{Potential Effect(s)} & Impact on customer if failure occurs & Joint loosens in service; wheel detaches\\\\\n\\textbf{Severity (S)} & 1-10 rating of effect seriousness (10 = safety/regulatory) & 10 (safety critical)\\\\\n\\textbf{Potential Cause(s)} & Root cause of the failure mode & Worn tool, wrong program, operator error\\\\\n\\addlinespace\n\\textbf{Occurrence (O)} & 1-10 rating of cause likelihood (10 = very frequent) & 4 (occasional occurrence)\\\\\n\\textbf{Current Controls} & Existing prevention or detection controls & Torque monitoring, error-proofing\\\\\n\\textbf{Detection (D)} & 1-10 rating of detection ability (10 = cannot detect) & 3 (high detection capability)\\\\\n\\textbf{RPN} & S × O × D = Risk Priority Number & 10 × 4 × 3 = 120\\\\\n\\textbf{Recommended Actions} & Actions to reduce S, O, or D & Add DC torque tool with automatic reject\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n**Action Priority Based on RPN:**\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/rpn-priority-1.pdf)\n:::\n:::\n\n\n::: {.example-box}\n**Example: Engine Block Machining PFMEA**\n\n| Step | Failure Mode | Effect | S | Cause | O | Control | D | RPN | Action |\n|:-----|:-------------|:-------|:--|:------|:--|:--------|:--|:----|:-------|\n| Bore cylinder | Oversize bore | Piston slap, oil consumption | 7 | Tool wear | 5 | SPC chart, tool life monitor | 4 | 140 | Add in-process bore gage |\n| Hone surface | Insufficient crosshatch | Poor ring seal, oil burning | 8 | Wrong hone stones | 3 | Visual inspection | 6 | 144 | Add surface roughness measurement |\n| Wash block | Residual chips | Engine seizure | 9 | Blocked nozzle | 4 | Cleanliness spec check | 5 | 180 | Add particle counter, automated flush verification |\n:::\n\n#### MSA: Measurement Systems Analysis\n\n**MSA** ensures that measurement systems provide reliable data for decision-making. Poor measurement systems can cause good parts to be rejected (false rejects) or bad parts to be accepted (false accepts).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/msa-components-1.pdf)\n:::\n:::\n\n\n**Gage R&R Study Acceptance Criteria:**\n\n| %GRR | Interpretation | Action |\n|:-----|:---------------|:-------|\n| < 10% | Excellent | Acceptable for all applications |\n| 10-30% | Acceptable | May be acceptable depending on application, cost of gage, cost of repairs |\n| > 30% | Unacceptable | Measurement system must be improved; cannot make reliable decisions |\n\n**Number of Distinct Categories (ndc):** Should be ≥ 5 to adequately discriminate between parts.\n\n::: {.example-box}\n**Example: Gage R&R Study for Shaft Diameter**\n\nA supplier conducts a Gage R&R study for a micrometer used to measure shaft diameter (spec: 25.00 ± 0.05 mm):\n\n**Study Setup:**\n- 3 operators measure 10 parts, 3 times each = 90 measurements\n- Parts selected to represent the range of production variation\n\n**Results:**\n| Source | Variance | % Contribution |\n|:-------|:---------|:---------------|\n| Part-to-Part | 0.000156 | 87.2% |\n| Repeatability | 0.000018 | 10.1% |\n| Reproducibility | 0.000005 | 2.7% |\n| **Total Gage R&R** | **0.000023** | **12.8%** |\n\n**Conclusion:** %GRR = 12.8% is acceptable (between 10-30%). ndc = 7 (≥5 required). The measurement system is adequate for this application.\n:::\n\n#### SPC: Statistical Process Control\n\n**SPC** uses control charts to monitor process stability and capability, distinguishing between common cause variation (inherent to the process) and special cause variation (assignable causes requiring investigation).\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/spc-chart-example-1.pdf)\n:::\n:::\n\n\n**Common Control Chart Types:**\n\n| Chart | Data Type | Monitors | When to Use |\n|:------|:----------|:---------|:------------|\n| X-bar & R | Variable, subgroups | Mean and range | Most common; subgroups of 2-10 |\n| X-bar & S | Variable, subgroups | Mean and std dev | Subgroups > 10 |\n| I-MR | Variable, individuals | Individual values and moving range | Slow processes, destructive testing |\n| p-chart | Attribute | Proportion defective | Variable sample sizes |\n| np-chart | Attribute | Number defective | Fixed sample sizes |\n| c-chart | Attribute | Count of defects | Fixed opportunity area |\n| u-chart | Attribute | Defects per unit | Variable opportunity area |\n\n**Process Capability Indices:**\n\n$$C_p = \\frac{USL - LSL}{6\\sigma}$$\n$$C_{pk} = \\min\\left(\\frac{USL - \\bar{x}}{3\\sigma}, \\frac{\\bar{x} - LSL}{3\\sigma}\\right)$$\n\n| Cpk Value | Interpretation | PPM Defective |\n|:----------|:---------------|:--------------|\n| < 1.00 | Not capable | > 2,700 |\n| 1.00 - 1.33 | Marginally capable | 64 - 2,700 |\n| 1.33 - 1.67 | Capable | 0.6 - 64 |\n| ≥ 1.67 | Highly capable (IATF requirement) | < 0.6 |\n\n::: {.example-box}\n**Example: SPC for Injection Molded Connector**\n\nA supplier monitors critical dimensions on an injection molded electrical connector:\n\n**Process Setup:**\n- Critical dimension: Pin spacing = 2.54 ± 0.08 mm\n- Sample 5 parts every 30 minutes\n- X-bar and R charts maintained at the press\n\n**Results over one shift:**\n- Process mean (X-double-bar) = 2.539 mm\n- Average range (R-bar) = 0.024 mm\n- Estimated σ = R-bar / d2 = 0.024 / 2.326 = 0.0103 mm\n\n**Capability:**\n- Cp = (2.62 - 2.46) / (6 × 0.0103) = 2.59\n- Cpk = min[(2.62 - 2.539)/(3 × 0.0103), (2.539 - 2.46)/(3 × 0.0103)] = min[2.62, 2.56] = **2.56**\n\n**Conclusion:** Cpk = 2.56 exceeds IATF requirement of 1.67. Process is highly capable.\n:::\n\n### AS9100D (Aerospace/Defense)\n\n**AS9100D** adds aerospace-specific requirements to ISO 9001:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}ll}\n\\caption{\\label{tab:as9100-additions}AS9100D Key Additional Requirements}\\\\\n\\toprule\nArea & Requirement\\\\\n\\midrule\n\\textbf{Configuration Management} & Control product configuration throughout lifecycle; change management\\\\\n\\textbf{First Article Inspection} & FAI per AS9102; documented verification of first production parts\\\\\n\\textbf{Counterfeit Parts Prevention} & Controls to prevent counterfeit parts entering supply chain\\\\\n\\textbf{Special Processes} & NADCAP accreditation for special processes (welding, heat treat, NDT)\\\\\n\\textbf{Product Safety} & Product safety requirements; reporting of unsafe conditions\\\\\n\\addlinespace\n\\textbf{Risk Management} & Explicit risk management process (often using AS/NZS 4360 or similar)\\\\\n\\textbf{Human Factors} & Consideration of human factors in process design\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### ISO 22000:2018 (Food Safety)\n\n**ISO 22000** integrates quality management with **HACCP** (Hazard Analysis Critical Control Points):\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}lll}\n\\caption{\\label{tab:iso22000-structure}ISO 22000 Food Safety Management Elements}\\\\\n\\toprule\nElement & Description & Example\\\\\n\\midrule\n\\textbf{Prerequisite Programs (PRPs)} & Basic hygiene conditions: cleaning, pest control, personnel hygiene, facility design & Sanitation schedule, hand washing stations, pest control contract\\\\\n\\textbf{Operational PRPs (OPRPs)} & PRPs essential to control specific identified hazards & Metal detector for physical hazard control\\\\\n\\textbf{HACCP Plan} & Critical Control Points (CCPs) for significant hazards; critical limits; monitoring & Pasteurization temperature ≥72°C for 15 seconds\\\\\n\\textbf{Traceability} & One-step-back, one-step-forward traceability; recall procedures & Lot coding, supplier records, distribution records\\\\\n\\textbf{Emergency Preparedness} & Procedures for food safety emergencies; recall/withdrawal & Product recall procedure, mock recall exercises\\\\\n\\addlinespace\n\\textbf{Validation and Verification} & Validate control measures; verify HACCP plan effectiveness & Challenge studies, environmental monitoring, internal audits\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n---\n\n## Documentation Requirements\n\nA QMS requires documented information to ensure consistency, provide evidence, and enable improvement.\n\n### Documentation Hierarchy\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/doc-hierarchy-1.pdf)\n:::\n:::\n\n\n### Document Control Requirements\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}lll}\n\\caption{\\label{tab:doc-control}Document Control Requirements (ISO 9001 Clause 7.5)}\\\\\n\\toprule\nRequirement & Description & Implementation\\\\\n\\midrule\n\\textbf{Approval} & Documents reviewed and approved for adequacy before issue & Approval signatures or electronic workflow\\\\\n\\textbf{Review \\& Update} & Reviewed, updated as necessary, and re-approved & Periodic review schedule; change request process\\\\\n\\textbf{Identification} & Identified with title, date, revision, author & Document numbering system; revision control\\\\\n\\textbf{Availability} & Relevant versions available at points of use & Controlled copies at workstations; electronic access\\\\\n\\textbf{Protection} & Protected from loss, damage, unauthorized changes & Backup systems; access controls; original storage\\\\\n\\addlinespace\n\\textbf{Obsolete Control} & Obsolete documents identified and prevented from unintended use & Stamp 'OBSOLETE'; remove from use; archive\\\\\n\\textbf{External Documents} & External documents identified and distribution controlled & List of external documents; master copy control\\\\\n\\textbf{Record Retention} & Records retained for specified periods; protected; retrievable & Retention matrix; secure storage; indexing\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Documented Information Required by ISO 9001:2015\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}lll}\n\\caption{\\label{tab:mandatory-docs}Documented Information Required by ISO 9001:2015}\\\\\n\\toprule\nType & Clause & Requirement\\\\\n\\midrule\n\\addlinespace[0.3em]\n\\multicolumn{3}{l}{\\cellcolor[HTML]{ebf5fb}{\\textbf{Documents (shall be maintained)}}}\\\\\n\\hspace{1em}\\textbf{Documents (shall be maintained)} & 4.3 & Scope of the QMS\\\\\n\\hspace{1em}\\textbf{Documents (shall be maintained)} & 5.2 & Quality policy\\\\\n\\hspace{1em}\\textbf{Documents (shall be maintained)} & 6.2 & Quality objectives\\\\\n\\hspace{1em}\\textbf{Documents (shall be maintained)} & 7.1.5 & Monitoring and measuring resources (calibration)\\\\\n\\hspace{1em}\\textbf{Documents (shall be maintained)} & 7.2 & Evidence of competence\\\\\n\\hspace{1em}\\textbf{Documents (shall be maintained)} & 8.1 & Evidence of conformity to processes\\\\\n\\hspace{1em}\\textbf{Documents (shall be maintained)} & 8.5.1 & Controlled conditions for production\\\\\n\\addlinespace[0.3em]\n\\multicolumn{3}{l}{\\cellcolor[HTML]{eafaf1}{\\textbf{Records (shall be retained)}}}\\\\\n\\hspace{1em}\\textbf{Records (shall be retained)} & 7.1.5.1 & Calibration/verification results\\\\\n\\hspace{1em}\\textbf{Records (shall be retained)} & 7.2 & Training records\\\\\n\\hspace{1em}\\textbf{Records (shall be retained)} & 8.2.3.2 & Results of review of requirements\\\\\n\\hspace{1em}\\textbf{Records (shall be retained)} & 8.3.3 & Design and development inputs\\\\\n\\hspace{1em}\\textbf{Records (shall be retained)} & 8.3.4 & Design and development controls\\\\\n\\hspace{1em}\\textbf{Records (shall be retained)} & 8.3.5 & Design and development outputs\\\\\n\\hspace{1em}\\textbf{Records (shall be retained)} & 8.3.6 & Design and development changes\\\\\n\\hspace{1em}\\textbf{Records (shall be retained)} & 8.5.2 & Traceability requirements\\\\\n\\hspace{1em}\\textbf{Records (shall be retained)} & 8.6 & Release of products/services\\\\\n\\hspace{1em}\\textbf{Records (shall be retained)} & 9.1.1 & Results of monitoring and measurement\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n---\n\n## Internal Auditing\n\n**Internal audits** are systematic, independent evaluations of the QMS to determine if it conforms to requirements and is effectively implemented.\n\n### The Audit Process\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/audit-process-1.pdf)\n:::\n:::\n\n\n### Audit Checklist Example\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}llll}\n\\caption{\\label{tab:audit-checklist}Sample Audit Checklist: Clause 7.1.5 Monitoring and Measuring Resources}\\\\\n\\toprule\nClause & Requirement & Question & Evidence\\\\\n\\midrule\n\\textbf{7.1.5} & Monitoring and measuring resources suitable for the type of activities & How do you determine what measuring equipment is needed? & Gauge selection procedure\\\\\n\\textbf{7.1.5} & Resources maintained to ensure continued fitness for purpose & What maintenance is performed on measuring equipment? & PM records\\\\\n\\textbf{7.1.5} & Documented information on fitness for purpose retained & Can you show me calibration records for this micrometer? & Calibration certificate\\\\\n\\textbf{7.1.5} & Measuring equipment identified to determine status & How can I tell if this gauge is currently calibrated? & Calibration stickers/tags\\\\\n\\textbf{7.1.5.2} & Measurement traceability when required & What standards are these gauges calibrated against? & Traceability certificates\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Types of Audit Findings\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}llll}\n\\caption{\\label{tab:finding-types}Types of Audit Findings}\\\\\n\\toprule\nFinding Type & Definition & Example & Action Required\\\\\n\\midrule\n\\cellcolor[HTML]{f8d7da}{\\textbf{Major Nonconformity}} & \\cellcolor[HTML]{f8d7da}{Absence or total breakdown of a system; significant risk to product/customer} & \\cellcolor[HTML]{f8d7da}{No calibration program exists; all gauges are uncontrolled} & \\cellcolor[HTML]{f8d7da}{Immediate corrective action; root cause analysis; may affect certification}\\\\\n\\cellcolor[HTML]{fff3cd}{\\textbf{Minor Nonconformity}} & \\cellcolor[HTML]{fff3cd}{Single lapse or isolated incident; system exists but not fully effective} & \\cellcolor[HTML]{fff3cd}{3 of 50 gauges found past due for calibration} & \\cellcolor[HTML]{fff3cd}{Corrective action required; typically 30-90 days}\\\\\n\\cellcolor[HTML]{d1ecf1}{\\textbf{Observation}} & \\cellcolor[HTML]{d1ecf1}{Weakness that could lead to nonconformity if not addressed} & \\cellcolor[HTML]{d1ecf1}{Calibration procedure doesn't specify what to do if gauge fails} & \\cellcolor[HTML]{d1ecf1}{No formal corrective action; monitor situation}\\\\\n\\cellcolor[HTML]{d4edda}{\\textbf{Opportunity for Improvement}} & \\cellcolor[HTML]{d4edda}{Suggestion for enhancement; not a nonconformity} & \\cellcolor[HTML]{d4edda}{Consider using electronic calibration records for faster retrieval} & \\cellcolor[HTML]{d4edda}{Consider for improvement; no requirement}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Auditor Competence\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}lll}\n\\caption{\\label{tab:auditor-competence}Internal Auditor Competency Requirements}\\\\\n\\toprule\nCompetency & Description & How\\_Developed\\\\\n\\midrule\n\\textbf{Knowledge of Standards} & Understanding of ISO 9001 and applicable industry standards & Training courses; self-study; certification (CQA, Lead Auditor)\\\\\n\\textbf{Audit Techniques} & Planning, interviewing, evidence collection, reporting & Auditor training; shadowing experienced auditors\\\\\n\\textbf{Industry Knowledge} & Understanding of processes, products, and industry practices & Work experience; process knowledge; technical training\\\\\n\\textbf{Communication Skills} & Active listening, clear questioning, professional writing & Practice; feedback; soft skills training\\\\\n\\textbf{Objectivity} & Independence from area being audited; impartial & Audit program design; rotation of assignments\\\\\n\\addlinespace\n\\textbf{Professional Judgment} & Ability to evaluate significance of findings & Experience; mentoring; calibration with other auditors\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n---\n\n## Corrective and Preventive Action (CAPA)\n\n**Corrective action** eliminates the cause of a detected nonconformity to prevent recurrence. **Preventive action** eliminates the cause of a potential nonconformity to prevent occurrence.\n\n### The CAPA Process\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/capa-process-1.pdf)\n:::\n:::\n\n\n#### Step 1: Identification\n\nThe CAPA process begins when a nonconformity or potential problem is identified. Sources include:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}ll>{}l}\n\\caption{\\label{tab:capa-sources}Common CAPA Initiation Sources}\\\\\n\\toprule\nSource & Description & Priority\\\\\n\\midrule\n\\textbf{Customer Complaints} & Product returns, warranty claims, customer feedback & High\\\\\n\\textbf{Internal Audits} & Nonconformities found during scheduled internal audits & Medium\\\\\n\\textbf{Process Monitoring} & SPC out-of-control conditions, trend analysis & Medium\\\\\n\\textbf{Inspection/Testing} & Failed inspections, test failures, rejected lots & High\\\\\n\\textbf{Supplier Issues} & Incoming inspection failures, supplier audit findings & Medium\\\\\n\\addlinespace\n\\textbf{Employee Reports} & Near-misses, safety concerns, improvement suggestions & Low-Medium\\\\\n\\textbf{Management Review} & Issues identified during management review meetings & Medium\\\\\n\\textbf{External Audits} & Findings from certification body or customer audits & High\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n#### Step 2: Evaluation\n\nEvaluate the significance of the issue to determine the appropriate response level:\n\n**Evaluation Criteria:**\n\n| Factor | Questions to Consider |\n|:-------|:----------------------|\n| **Safety** | Could this harm people or the environment? |\n| **Customer Impact** | How many customers affected? Severity of impact? |\n| **Regulatory** | Does this violate regulations or standards? |\n| **Financial** | What is the cost of the problem? Potential liability? |\n| **Frequency** | Is this a one-time event or recurring pattern? |\n| **Detection** | How was it found? Could others exist undetected? |\n\n**Containment Actions** - Immediate actions to limit the impact while the investigation proceeds:\n\n- Quarantine suspect product\n- Sort and inspect inventory\n- Notify affected customers\n- Implement temporary controls\n- Stop shipments if necessary\n\n::: {.example-box}\n**Example: Evaluation of Dimensional Nonconformity**\n\nA batch of machined shafts is found with diameter 0.02 mm oversize:\n\n- **Safety**: Low - not a safety-critical dimension\n- **Customer Impact**: Medium - may cause assembly issues\n- **Regulatory**: None\n- **Financial**: 500 parts × $15/part = $7,500 potential scrap\n- **Containment**: Quarantine batch, 100% inspection of last 3 lots, notify customer\n\n**Decision**: Proceed with formal CAPA (cost exceeds $5,000 threshold)\n:::\n\n#### Step 3: Investigation\n\nGather all relevant data and evidence to understand what happened:\n\n**Investigation Activities:**\n\n- **Review documentation**: Work instructions, control plans, inspection records\n- **Examine physical evidence**: Failed parts, raw materials, tooling\n- **Interview personnel**: Operators, inspectors, supervisors\n- **Analyze data**: SPC charts, measurement data, process parameters\n- **Timeline reconstruction**: When did the problem start? What changed?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}lll}\n\\caption{\\label{tab:investigation-data}Data Collection for CAPA Investigation}\\\\\n\\toprule\nData Type & Examples & Collection Method\\\\\n\\midrule\n\\textbf{Process Data} & Temperatures, pressures, speeds, feeds, cycle times & Data historians, SPC software, log sheets\\\\\n\\textbf{Material Data} & Lot numbers, certificates, incoming inspection results & Traceability system, supplier records\\\\\n\\textbf{Equipment Data} & Maintenance records, calibration status, tool wear & CMMS, calibration database\\\\\n\\textbf{Personnel Data} & Training records, shift assignments, experience level & HR system, training matrix\\\\\n\\textbf{Environmental Data} & Temperature, humidity, contamination levels & Environmental monitoring system\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n#### Step 4: Root Cause Analysis\n\nDetermine the fundamental cause(s) of the problem using structured analysis tools:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/rca-tools-1.pdf)\n:::\n:::\n\n\n**The 5 Whys Example:**\n\n| Level | Question | Answer |\n|:------|:---------|:-------|\n| Problem | Shaft diameter is oversize | - |\n| Why 1? | Why is the diameter oversize? | Tool is worn |\n| Why 2? | Why is the tool worn? | Tool wasn't changed at scheduled interval |\n| Why 3? | Why wasn't it changed? | Operator didn't know it was due |\n| Why 4? | Why didn't operator know? | Tool life counter was reset incorrectly |\n| Why 5? | Why was it reset incorrectly? | No verification step in setup procedure |\n| **Root Cause** | **Setup procedure lacks tool counter verification step** | |\n\n**The 6M Categories (Fishbone Diagram):**\n\n- **Man** (People): Training, skills, fatigue, attention\n- **Machine**: Equipment condition, capability, maintenance\n- **Material**: Raw material quality, specifications, storage\n- **Method**: Procedures, work instructions, standards\n- **Measurement**: Gages, calibration, measurement technique\n- **Mother Nature** (Environment): Temperature, humidity, contamination\n\n#### Step 5: Action Plan\n\nDefine specific corrective and/or preventive actions to address the root cause:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}llll}\n\\caption{\\label{tab:action-types}Types of CAPA Actions}\\\\\n\\toprule\nAction\\_Type & Definition & Example & Timeframe\\\\\n\\midrule\n\\textbf{Correction} & Fix the immediate problem (symptom treatment) & Rework or scrap the nonconforming parts & Immediate\\\\\n\\textbf{Corrective Action} & Eliminate the root cause to prevent recurrence & Revise setup procedure to include tool counter verification & 30-90 days typical\\\\\n\\textbf{Preventive Action} & Eliminate potential causes before problems occur & Add tool counter verification to ALL machine setup procedures & Ongoing improvement\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n**SMART Action Planning:**\n\n- **S**pecific: Clearly defined action (not vague)\n- **M**easurable: Can verify completion and effectiveness\n- **A**ssignable: Single owner responsible\n- **R**ealistic: Achievable with available resources\n- **T**ime-bound: Due date specified\n\n::: {.example-box}\n**Example: SMART Corrective Action**\n\n**Poor**: \"Improve the setup procedure\"\n\n**SMART**: \"Quality Engineer (J. Smith) will revise Work Instruction WI-2345 to add Step 4.7: 'Verify tool life counter matches Tool Setup Sheet before starting production. Record counter reading on Setup Checklist Form F-102.' Revision to be completed by April 15, training completed by April 22.\"\n:::\n\n#### Step 6: Implementation\n\nExecute the action plan with clear ownership and tracking:\n\n**Implementation Requirements:**\n\n- Assign responsible person for each action\n- Provide necessary resources (time, budget, authority)\n- Communicate changes to affected personnel\n- Update documentation (procedures, work instructions, forms)\n- Train personnel on new requirements\n- Implement changes in a controlled manner\n\n**Change Control Considerations:**\n\n| Change Type | Approval Required | Documentation |\n|:------------|:------------------|:--------------|\n| Document revision | Document owner, Quality | Revision history, training records |\n| Process change | Process owner, Engineering, Quality | Change request, validation if needed |\n| Equipment change | Maintenance, Engineering, Quality | Equipment qualification, capability study |\n| Product change | Engineering, Quality, Customer (if required) | ECN, customer approval, PPAP if applicable |\n\n#### Step 7: Verification\n\nVerify that actions were completed AND effective:\n\n**Completion Verification:**\n- Was the action actually implemented?\n- Is documentation updated and approved?\n- Are personnel trained?\n- Is the change being followed?\n\n**Effectiveness Verification:**\n- Has the problem stopped recurring?\n- Do metrics show improvement?\n- Are there any unintended consequences?\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}lll}\n\\caption{\\label{tab:verification-methods}CAPA Effectiveness Verification Methods}\\\\\n\\toprule\nMethod & Description & When\\_to\\_Use\\\\\n\\midrule\n\\textbf{Monitoring Period} & Track for recurrence over defined period (e.g., 90 days, 3 production runs) & All CAPAs - minimum requirement\\\\\n\\textbf{Statistical Analysis} & Compare defect rates before/after; statistical significance testing & When baseline data exists\\\\\n\\textbf{Audit Verification} & Include in next internal audit; verify implementation & Process/documentation changes\\\\\n\\textbf{Customer Feedback} & Monitor complaints related to this issue & Customer-reported issues\\\\\n\\textbf{Process Capability} & Cpk study to confirm process improvement & Manufacturing process changes\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n#### Step 8: Closure\n\nComplete documentation and share lessons learned:\n\n**Closure Requirements:**\n\n- All actions verified complete\n- Effectiveness confirmed (no recurrence)\n- Documentation updated and approved\n- CAPA record completed with all evidence\n- Management approval for closure\n\n**Lessons Learned:**\n\n- What was the root cause?\n- Could this happen elsewhere? (Horizontal deployment)\n- Should procedures/training be updated system-wide?\n- Are there similar products/processes at risk?\n- What can we do to prevent similar issues?\n\n::: {.example-box}\n**Example: Horizontal Deployment**\n\nThe shaft diameter CAPA revealed that setup procedures lacked tool counter verification.\n\n**Horizontal deployment**: Quality reviewed ALL 47 CNC machine setup procedures and found 12 others with the same gap. All procedures were revised, and the finding was shared at the monthly quality meeting as a lesson learned.\n:::\n\n### CAPA Effectiveness Criteria\n\nThis worked example is fixed as a reference — read through it once, then try the *editable* example further on in this chapter for yourself.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CAPA Effectiveness Tracking\nset.seed(42)\n\n# Simulate CAPA data for a year\nmonths <- c(\"Jan\", \"Feb\", \"Mar\", \"Apr\", \"May\", \"Jun\",\n            \"Jul\", \"Aug\", \"Sep\", \"Oct\", \"Nov\", \"Dec\")\n\ncapa_data <- data.frame(\n  Month = factor(months, levels = months),\n  Total_CAPAs = c(12, 15, 18, 14, 11, 13, 10, 9, 8, 7, 9, 6),\n  Closed_On_Time = c(8, 10, 12, 11, 9, 11, 9, 8, 7, 6, 8, 5),\n  Effective = c(7, 9, 10, 10, 8, 10, 8, 8, 7, 6, 8, 5),\n  Recurrence = c(2, 1, 3, 1, 0, 1, 0, 0, 1, 0, 0, 0)\n)\n\n# Calculate metrics\ncapa_data$On_Time_Rate <- round(capa_data$Closed_On_Time / capa_data$Total_CAPAs * 100, 1)\ncapa_data$Effectiveness_Rate <- round(capa_data$Effective / capa_data$Closed_On_Time * 100, 1)\n\ncat(\"CAPA Performance Metrics Summary:\\n\")\ncat(\"─────────────────────────────────\\n\")\ncat(\"Total CAPAs initiated:\", sum(capa_data$Total_CAPAs), \"\\n\")\ncat(\"Closed on time:\", sum(capa_data$Closed_On_Time), \"(\",\n    round(sum(capa_data$Closed_On_Time)/sum(capa_data$Total_CAPAs)*100, 1), \"%)\\n\")\ncat(\"Verified effective:\", sum(capa_data$Effective), \"(\",\n    round(sum(capa_data$Effective)/sum(capa_data$Closed_On_Time)*100, 1), \"%)\\n\")\ncat(\"Recurrences:\", sum(capa_data$Recurrence), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCAPA Performance Metrics Summary:\n─────────────────────────────────\nTotal CAPAs initiated: 132 \nClosed on time: 104 ( 78.8 %)\nVerified effective: 96 ( 92.3 %)\nRecurrences: 9 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/capa-chart-1.pdf)\n:::\n:::\n\n\n---\n\n## Management Review\n\n**Management review** is a formal evaluation of the QMS by top management to ensure its continuing suitability, adequacy, and effectiveness.\n\n### Management Review Inputs\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}lll}\n\\caption{\\label{tab:mgmt-review-inputs}Management Review Inputs (ISO 9001 Clause 9.3.2)}\\\\\n\\toprule\nRequired Input & Details to Review & Typical Data Sources\\\\\n\\midrule\n\\textbf{Previous Review Actions} & Status of actions from previous management reviews & Previous meeting minutes; action log\\\\\n\\textbf{Changes in Issues/Context} & Changes in external/internal issues; interested party requirements & SWOT analysis; customer feedback; regulatory changes\\\\\n\\textbf{Quality Performance} & Customer satisfaction; quality objectives achievement; process performance; nonconformities; audits; supplier performance & KPI dashboards; audit reports; CAPA data; customer complaints\\\\\n\\textbf{Resource Adequacy} & Adequacy of resources for QMS maintenance and improvement & Budget status; staffing levels; equipment condition\\\\\n\\textbf{Risk/Opportunity Actions} & Effectiveness of actions taken to address risks and opportunities & Risk register updates; opportunity tracking\\\\\n\\addlinespace\n\\textbf{Improvement Opportunities} & Opportunities for improvement identified from various sources & Employee suggestions; benchmarking; industry developments\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Management Review Outputs\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}lll}\n\\caption{\\label{tab:mgmt-review-outputs}Management Review Outputs (ISO 9001 Clause 9.3.3)}\\\\\n\\toprule\nRequired Output & ISO Requirement & Examples\\\\\n\\midrule\n\\textbf{Improvement Decisions} & Decisions and actions related to improvement opportunities & Launch kaizen project for top 3 customer complaints; implement new quality training program\\\\\n\\textbf{QMS Changes} & Any need for changes to the QMS & Revise control plan based on PFMEA update; modify inspection frequency\\\\\n\\textbf{Resource Needs} & Any resource needs & Hire additional quality technician; purchase new CMM; upgrade software\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Sample Management Review Dashboard\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/mgmt-dashboard-1.pdf)\n:::\n:::\n\n\n---\n\n## Continuous Improvement\n\n**Continuous improvement** is a fundamental principle of quality management - the ongoing effort to improve products, services, and processes.\n\n### Improvement Methodologies\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}llll}\n\\caption{\\label{tab:improvement-methods}Continuous Improvement Methodologies}\\\\\n\\toprule\nMethodology & Origin & Best\\_For & Steps\\\\\n\\midrule\n\\textbf{PDCA} & Deming/Shewhart & General improvement cycle; process changes & Plan-Do-Check-Act\\\\\n\\textbf{DMAIC} & Six Sigma & Data-driven problem solving; reducing variation & Define-Measure-Analyze-Improve-Control\\\\\n\\textbf{Kaizen} & Toyota/Lean & Small, incremental improvements; team-based & Identify waste → Improve → Standardize\\\\\n\\textbf{A3 Problem Solving} & Toyota & Visual problem solving; root cause analysis & Background → Goals → Analysis → Countermeasures → Follow-up\\\\\n\\textbf{8D} & Ford & Customer complaints; complex problems & D0-D8 (Team, Problem, Containment, Root Cause, Actions, Verify, Prevent, Close)\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Key Performance Indicators (KPIs)\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}llll}\n\\caption{\\label{tab:kpi-examples}Common Quality Management KPIs}\\\\\n\\toprule\nCategory & KPI & Formula & Target\\\\\n\\midrule\n\\addlinespace[0.3em]\n\\multicolumn{4}{l}{\\cellcolor[HTML]{ebf5fb}{\\textbf{Quality Metrics}}}\\\\\n\\hspace{1em}\\textbf{Quality} & First Pass Yield (FPY) & (Good units first time / Total units) × 100\\% & ≥98\\%\\\\\n\\hspace{1em}\\textbf{Quality} & Customer Complaints (PPM) & (Complaints / Units shipped) × 1,000,000 & <100\\\\\n\\hspace{1em}\\textbf{Quality} & Internal Reject Rate & (Rejected units / Total inspected) × 100\\% & <1\\%\\\\\n\\hspace{1em}\\textbf{Quality} & Cost of Quality & Prevention + Appraisal + Internal Failure + External Failure & <3\\% of sales\\\\\n\\addlinespace[0.3em]\n\\multicolumn{4}{l}{\\cellcolor[HTML]{eafaf1}{\\textbf{Delivery Metrics}}}\\\\\n\\hspace{1em}\\textbf{Delivery} & On-Time Delivery (OTD) & (Orders delivered on time / Total orders) × 100\\% & ≥98\\%\\\\\n\\hspace{1em}\\textbf{Delivery} & Lead Time & Order date to delivery date & Industry benchmark\\\\\n\\hspace{1em}\\textbf{Delivery} & Order Fulfillment Rate & (Complete orders shipped / Total orders) × 100\\% & ≥99\\%\\\\\n\\addlinespace[0.3em]\n\\multicolumn{4}{l}{\\cellcolor[HTML]{fef9e7}{\\textbf{Cost Metrics}}}\\\\\n\\hspace{1em}\\textbf{Cost} & Scrap Rate & (Scrap value / Total production value) × 100\\% & <2\\%\\\\\n\\hspace{1em}\\textbf{Cost} & Rework Cost & Labor + Material for rework & Minimize\\\\\n\\hspace{1em}\\textbf{Cost} & Warranty Cost & Warranty claims cost / Revenue & <0.5\\% of sales\\\\\n\\addlinespace[0.3em]\n\\multicolumn{4}{l}{\\cellcolor[HTML]{fdedec}{\\textbf{Safety Metrics}}}\\\\\n\\hspace{1em}\\textbf{Safety} & Recordable Incident Rate & (Recordable incidents × 200,000) / Hours worked & <1.0\\\\\n\\hspace{1em}\\textbf{Safety} & Near Miss Reports & Count of near miss reports & Encourage reporting\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Cost of Quality (COQ)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Cost of Quality Analysis\ncoq_data <- data.frame(\n  Category = c(\"Prevention\", \"Appraisal\", \"Internal Failure\", \"External Failure\"),\n  Description = c(\"Quality planning, training, process control\",\n                  \"Inspection, testing, audits, calibration\",\n                  \"Scrap, rework, reinspection, downtime\",\n                  \"Warranty, returns, complaints, recalls\"),\n  Cost = c(50000, 75000, 120000, 180000)\n)\n\ntotal_coq <- sum(coq_data$Cost)\nrevenue <- 10000000  # $10M revenue\n\ncoq_data$Percent_of_COQ <- round(coq_data$Cost / total_coq * 100, 1)\ncoq_data$Percent_of_Revenue <- round(coq_data$Cost / revenue * 100, 2)\n\ncat(\"Cost of Quality Analysis:\\n\")\ncat(\"─────────────────────────────\\n\")\nprint(coq_data[, c(\"Category\", \"Cost\", \"Percent_of_COQ\")])\ncat(\"─────────────────────────────\\n\")\ncat(\"Total Cost of Quality: $\", format(total_coq, big.mark = \" \"), \"\\n\")\ncat(\"COQ as % of Revenue:\", round(total_coq/revenue*100, 1), \"%\\n\\n\")\n\n# Analysis\nconformance <- coq_data$Cost[1] + coq_data$Cost[2]\nnonconformance <- coq_data$Cost[3] + coq_data$Cost[4]\n\ncat(\"Conformance Costs (Prevention + Appraisal): $\", format(conformance, big.mark = \" \"),\n    \"(\", round(conformance/total_coq*100, 1), \"%)\\n\")\ncat(\"Nonconformance Costs (Failures): $\", format(nonconformance, big.mark = \" \"),\n    \"(\", round(nonconformance/total_coq*100, 1), \"%)\\n\")\ncat(\"\\nRecommendation: Increase prevention spending to reduce failure costs\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCost of Quality Analysis:\n─────────────────────────────\n          Category   Cost Percent_of_COQ\n1       Prevention  50000           11.8\n2        Appraisal  75000           17.6\n3 Internal Failure 120000           28.2\n4 External Failure 180000           42.4\n─────────────────────────────\nTotal Cost of Quality: $ 425 000 \nCOQ as % of Revenue: 4.2 %\n\nConformance Costs (Prevention + Appraisal): $ 125 000 ( 29.4 %)\nNonconformance Costs (Failures): $ 3e+05 ( 70.6 %)\n\nRecommendation: Increase prevention spending to reduce failure costs\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 1 row containing missing values or values outside the scale range\n(`geom_text()`).\nRemoved 1 row containing missing values or values outside the scale range\n(`geom_text()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/coq-chart-1.pdf)\n:::\n:::\n\n\n---\n\n## Integration with Quality Tools\n\nA mature QMS integrates various quality tools throughout the organization.\n\n### Quality Tools Integration Map\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/tools-integration-1.pdf)\n:::\n:::\n\n\n### Linking Tools to QMS Requirements\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}llll}\n\\caption{\\label{tab:tools-qms-link}Quality Tools and QMS Integration}\\\\\n\\toprule\nQuality Tool & ISO 9001 Clause & Purpose & Output Feeds Into\\\\\n\\midrule\n\\textbf{PFMEA} & 6.1, 8.1 & Identify and mitigate process risks before production & Control Plan, Work Instructions\\\\\n\\textbf{Control Plan} & 8.1, 8.5.1 & Define controls for special characteristics & Work Instructions, SPC requirements\\\\\n\\textbf{SPC} & 9.1.1 & Monitor process performance; detect special causes & CAPA triggers, Management Review\\\\\n\\textbf{MSA} & 7.1.5 & Ensure measurement system is adequate & SPC validity, Control Plan\\\\\n\\textbf{Internal Audit} & 9.2 & Verify QMS conformance and effectiveness & CAPA triggers, Management Review\\\\\n\\addlinespace\n\\textbf{CAPA} & 10.2 & Eliminate causes of nonconformities & Process improvements, Lessons learned\\\\\n\\textbf{Management Review} & 9.3 & Evaluate QMS suitability and effectiveness & Strategic decisions, Resource allocation\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n---\n\n## Certification Process\n\nOrganizations can seek **third-party certification** to demonstrate QMS conformance to customers and stakeholders.\n\n### The Certification Journey\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_segment(aes(x = 1, xend = 8, y = 1, yend = 1), color = \"gray70\", : All aesthetics have length 1, but the data has 8 rows.\ni Please consider using `annotate()` or provide this layer with data containing\n  a single row.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](13-Quality-Systems_files/figure-pdf/certification-process-1.pdf)\n:::\n:::\n\n\n### Certification Audit Types\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{}llll}\n\\caption{\\label{tab:audit-types}Third-Party Certification Audit Types}\\\\\n\\toprule\nAudit Type & Purpose & Focus Areas & Duration\\\\\n\\midrule\n\\textbf{Stage 1 (Documentation)} & Review QMS documentation; verify readiness for Stage 2 & Quality manual, procedures, scope, internal audits, management review & 0.5-1 day (remote or on-site)\\\\\n\\textbf{Stage 2 (Certification)} & Evaluate implementation and effectiveness of QMS & All clauses; process effectiveness; records; interviews & 2-5 days depending on size\\\\\n\\textbf{Surveillance} & Verify continued conformance (annual) & Selected processes; previous findings; changes & 1-2 days annually\\\\\n\\textbf{Recertification} & Full re-audit at end of 3-year cycle & Complete review similar to Stage 2 & 2-4 days\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n---\n\n## Video Resources\n\n### ISO 9001:2015 Overview\n\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/O5T4H8K_rwQ\" title=\"ISO 9001:2015 Overview\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\n\n### Internal Auditing Best Practices\n\n<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/deRqslBeMrE\" title=\"Internal Auditing\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\n\n---\n\n## Summary\n\nA Quality Management System provides the framework for consistently meeting customer requirements and improving organizational performance:\n\n1. **ISO 9001:2015** provides the foundational requirements using risk-based thinking and PDCA\n2. **Industry standards** (IATF 16949, AS9100, ISO 22000) add sector-specific requirements\n3. **Documentation** establishes the hierarchy from policy to procedures to records\n4. **Internal audits** verify conformance and identify improvement opportunities\n5. **CAPA** eliminates root causes of nonconformities and prevents recurrence\n6. **Management review** ensures QMS suitability and drives strategic improvement\n7. **Continuous improvement** is embedded through KPIs, COQ analysis, and improvement methodologies\n8. **Quality tools** (PFMEA, SPC, MSA) integrate throughout the product lifecycle\n\n> \"Quality is not an act, it is a habit.\" — Aristotle\n\n---\n\n## Review Questions\n\n<details><summary>**Question 1**: Explain the seven quality management principles and how they relate to each other.</summary>\n\n**Answer:**\n\nThe seven quality management principles form an interconnected foundation:\n\n1. **Customer Focus** (Central principle)\n   - Understanding and meeting customer needs is the primary purpose\n   - All other principles support this goal\n\n2. **Leadership**\n   - Leaders establish unity of purpose and direction\n   - Create conditions for people to achieve quality objectives\n   - Enables all other principles\n\n3. **Engagement of People**\n   - Competent, empowered people at all levels\n   - Essential for effective processes and customer focus\n\n4. **Process Approach**\n   - Activities managed as interrelated processes\n   - Enables consistent, predictable results\n\n5. **Improvement**\n   - Ongoing focus on enhancing performance\n   - Essential for maintaining customer satisfaction\n\n6. **Evidence-based Decision Making**\n   - Decisions based on analysis of data\n   - Reduces uncertainty; improves decision quality\n\n7. **Relationship Management**\n   - Managing relationships with interested parties (suppliers, partners)\n   - Optimizes their impact on performance\n\n**Relationships:**\n- Customer Focus drives the need for all others\n- Leadership enables and supports all principles\n- Engagement of People is essential for Process Approach and Improvement\n- Evidence-based Decision Making supports Improvement\n- Relationship Management extends quality beyond the organization\n</details>\n\n<details><summary>**Question 2**: Compare ISO 9001, IATF 16949, and AS9100. When would each be required?</summary>\n\n**Answer:**\n\n| Standard | Base | Industry | Additional Focus |\n|----------|------|----------|------------------|\n| **ISO 9001:2015** | Standalone | General | Quality fundamentals |\n| **IATF 16949:2016** | ISO 9001 + automotive | Automotive | PPAP, APQP, Core Tools |\n| **AS9100D** | ISO 9001 + aerospace | Aerospace/Defense | Configuration mgmt, FAI, counterfeit prevention |\n\n**When Required:**\n\n**ISO 9001:**\n- Any organization wanting to demonstrate quality capability\n- Customer or contract requirement for QMS certification\n- Basis for all other standards\n- Suitable for service, manufacturing, any industry\n\n**IATF 16949:**\n- Suppliers to automotive OEMs (Ford, GM, Toyota, VW, etc.)\n- Required for production parts/materials\n- Required throughout automotive supply chain\n- Includes Customer-Specific Requirements (CSRs)\n\n**AS9100:**\n- Suppliers to aerospace/defense contractors\n- Boeing, Airbus, Lockheed Martin, military programs\n- Required for flight-critical components\n- OASIS database registration required\n\n**Key Differences:**\n- IATF 16949: Emphasizes PPAP, APQP, manufacturing process control\n- AS9100: Emphasizes traceability, configuration control, first article inspection\n- Both build on ISO 9001 with sector-specific additions\n</details>\n\n<details><summary>**Question 3**: Describe the documentation hierarchy in a QMS. Give an example of each level.</summary>\n\n**Answer:**\n\n**Level 1: Quality Policy and Objectives**\n- Strategic direction for quality\n- Signed by top management\n- Communicated to all employees\n- *Example:* \"ABC Company is committed to delivering defect-free products that meet customer requirements through continuous improvement of our processes and people.\"\n\n**Level 2: Quality Manual and Procedures**\n- Describes WHAT is done and WHO is responsible\n- System-level documents\n- *Example:* Document Control Procedure (QP-001)\n  - Purpose: Control creation, approval, distribution of documents\n  - Scope: All QMS documents\n  - Responsibilities: Document Control Coordinator, Department Managers\n  - Process flow for document changes\n\n**Level 3: Work Instructions and Specifications**\n- Describes HOW tasks are performed\n- Detailed step-by-step instructions\n- *Example:* Work Instruction for CNC Lathe Setup (WI-MAC-015)\n  - Step 1: Verify program number matches work order\n  - Step 2: Install correct tooling per setup sheet\n  - Step 3: Set tool offsets using touch-off procedure\n  - Step 4: Run first piece and verify dimensions\n\n**Level 4: Records and Forms**\n- Evidence that activities were performed\n- Completed forms, inspection results, logs\n- *Example:* First Article Inspection Report (FM-QC-008)\n  - Part number, revision, date\n  - Dimensional measurements vs. specifications\n  - Inspector signature\n  - Disposition (Accept/Reject)\n</details>\n\n<details><summary>**Question 4**: What are the key elements of an effective internal audit program?</summary>\n\n**Answer:**\n\n**1. Audit Program Planning**\n- Annual audit schedule covering all QMS processes\n- Risk-based frequency (higher risk = more frequent)\n- Documented audit program procedure\n- Resource allocation (trained auditors, time)\n\n**2. Auditor Competence**\n- Trained in audit techniques\n- Knowledge of standards (ISO 9001, industry-specific)\n- Understanding of processes being audited\n- Independence from area being audited\n\n**3. Audit Preparation**\n- Review of relevant documents (procedures, previous audits)\n- Prepared checklist linked to requirements\n- Notification to auditee\n- Defined scope and objectives\n\n**4. Audit Execution**\n- Opening meeting (purpose, scope, schedule)\n- Evidence collection (documents, records, interviews, observation)\n- Objective evaluation against criteria\n- Note taking and evidence documentation\n\n**5. Reporting**\n- Clear finding statements (nonconformities, observations)\n- Reference to requirement violated\n- Objective evidence cited\n- Closing meeting to present findings\n\n**6. Follow-up**\n- Corrective action requests issued\n- Root cause analysis required\n- Verification of corrective action implementation\n- Verification of effectiveness\n\n**7. Continuous Improvement of Audit Program**\n- Evaluate audit program effectiveness\n- Update based on organizational changes\n- Calibrate auditors periodically\n- Incorporate lessons learned\n</details>\n\n<details><summary>**Question 5**: Explain the difference between corrective action and preventive action. Provide an example of each.</summary>\n\n**Answer:**\n\n**Corrective Action:**\n- Eliminates the cause of a *detected* nonconformity\n- Reactive - responds to something that has already happened\n- Goal: Prevent recurrence of the specific problem\n\n*Example:*\n- **Nonconformity:** Customer received shipment with wrong part numbers (3 incidents in past month)\n- **Root Cause:** Shipping labels printed from outdated part number list\n- **Corrective Action:**\n  1. Update master part number list\n  2. Link shipping system directly to ERP for current data\n  3. Add verification step comparing label to packing list\n- **Verification:** No recurrence after 3 months\n\n**Preventive Action:**\n- Eliminates the cause of a *potential* nonconformity\n- Proactive - addresses something that hasn't happened yet\n- Goal: Prevent occurrence before it happens\n\n*Example:*\n- **Potential Nonconformity:** New CNC machine may produce out-of-spec parts due to operator unfamiliarity\n- **Risk Identified Through:** PFMEA analysis during new equipment installation\n- **Preventive Action:**\n  1. Develop comprehensive training program before machine goes live\n  2. Create detailed setup procedures with photos\n  3. Implement first-article inspection for first 30 days\n  4. Assign experienced mentor to new operators\n- **Verification:** Track first-pass yield during initial production period\n\n**Key Difference:**\n- Corrective = Fix what went wrong\n- Preventive = Stop what might go wrong\n\n**Note:** ISO 9001:2015 doesn't explicitly require \"preventive action\" as a separate process. Instead, risk-based thinking throughout the QMS serves the preventive function.\n</details>\n\n<details><summary>**Question 6**: Calculate and analyze the Cost of Quality for the following data. What recommendations would you make?</summary>\n\n| Category | Cost |\n|----------|------|\n| Quality planning | $35,000 |\n| Training | $25,000 |\n| Incoming inspection | $40,000 |\n| In-process inspection | $55,000 |\n| Final inspection | $30,000 |\n| Scrap | $85,000 |\n| Rework | $65,000 |\n| Warranty claims | $120,000 |\n| Customer returns | $45,000 |\n\nAnnual revenue: $8,000,000\n\n**Answer:** (live — change the cost figures to check your own version)\n\n```{webr-r}\n#| label: q6-answer\n# Cost of Quality Analysis\nprevention <- 35000 + 25000  # Planning + Training\nappraisal <- 40000 + 55000 + 30000  # Inspections\ninternal_failure <- 85000 + 65000  # Scrap + Rework\nexternal_failure <- 120000 + 45000  # Warranty + Returns\n\ntotal_coq <- prevention + appraisal + internal_failure + external_failure\nrevenue <- 8000000\n\ncat(\"Cost of Quality Breakdown:\\n\")\ncat(\"─────────────────────────────\\n\")\ncat(\"Prevention:       $\", format(prevention, big.mark = \" \"),\n    \"(\", round(prevention/total_coq*100, 1), \"%)\\n\")\ncat(\"Appraisal:        $\", format(appraisal, big.mark = \" \"),\n    \"(\", round(appraisal/total_coq*100, 1), \"%)\\n\")\ncat(\"Internal Failure: $\", format(internal_failure, big.mark = \" \"),\n    \"(\", round(internal_failure/total_coq*100, 1), \"%)\\n\")\ncat(\"External Failure: $\", format(external_failure, big.mark = \" \"),\n    \"(\", round(external_failure/total_coq*100, 1), \"%)\\n\")\ncat(\"─────────────────────────────\\n\")\ncat(\"Total COQ:        $\", format(total_coq, big.mark = \" \"), \"\\n\")\ncat(\"COQ % of Revenue:\", round(total_coq/revenue*100, 1), \"%\\n\\n\")\n\nconformance <- prevention + appraisal\nnonconformance <- internal_failure + external_failure\n\ncat(\"Conformance Costs:    $\", format(conformance, big.mark = \" \"),\n    \"(\", round(conformance/total_coq*100, 1), \"%)\\n\")\ncat(\"Nonconformance Costs: $\", format(nonconformance, big.mark = \" \"),\n    \"(\", round(nonconformance/total_coq*100, 1), \"%)\\n\")\n```\n\n**Analysis:**\n- COQ at 7.5% of revenue is HIGH (target <3%)\n- External failure costs are the largest category (27.5%)\n- Nonconformance costs (60.8%) greatly exceed conformance (39.2%)\n- Prevention is only 10% of COQ - very low\n\n**Recommendations:**\n1. **Increase Prevention Investment:**\n   - Implement SPC on critical processes to reduce defects\n   - Enhance operator training on quality standards\n   - Apply PFMEA to identify and control failure modes\n\n2. **Reduce External Failures:**\n   - Analyze warranty data for root causes\n   - Improve final inspection effectiveness\n   - Implement containment for known issues\n\n3. **Optimize Appraisal:**\n   - Use SPC to reduce inspection where processes are capable\n   - Implement risk-based inspection (more for critical, less for proven)\n\n4. **Target COQ Reduction:**\n   - Short-term: Reduce external failures by 50% ($82,500 savings)\n   - Medium-term: Reduce internal failures by 30% ($45,000 savings)\n   - Long-term: Achieve COQ <3% of revenue ($240,000)\n</details>\n\n<details><summary>**Question 7**: What is risk-based thinking in ISO 9001:2015? How is it different from formal risk management?</summary>\n\n**Answer:**\n\n**Risk-Based Thinking in ISO 9001:2015:**\n\nRisk-based thinking is a way of considering risks and opportunities when designing, implementing, and operating the QMS. It:\n\n- Applies throughout the standard (not a separate clause)\n- Is proportional to potential impact on conformity\n- Makes preventive action part of routine planning\n- Considers both risks (negative) and opportunities (positive)\n\n**Where Risk-Based Thinking Applies:**\n\n| Clause | Application |\n|--------|-------------|\n| 4.1 Context | Identify external/internal issues affecting QMS |\n| 4.2 Interested Parties | Understand requirements that could impact quality |\n| 6.1 Planning | Plan actions to address risks and opportunities |\n| 8.1 Operations | Consider risks in operational planning |\n| 9.1 Performance | Monitor effectiveness of risk actions |\n| 10.2 Corrective Action | Update risks/opportunities based on nonconformities |\n\n**How It Differs from Formal Risk Management:**\n\n| Aspect | Risk-Based Thinking | Formal Risk Management |\n|--------|---------------------|------------------------|\n| Requirement | Implicit throughout ISO 9001 | Explicit (ISO 31000) |\n| Documentation | No formal risk register required | Documented risk register |\n| Methodology | No specific method required | Defined methodology (FMEA, etc.) |\n| Quantification | Not required | Often quantitative |\n| Scope | QMS processes | Enterprise-wide |\n\n**Practical Implementation:**\n\nOrganizations should:\n1. Consider risks when designing processes\n2. Build controls proportional to risk level\n3. Monitor and review effectiveness\n4. Update as context changes\n\nISO 9001 does NOT require:\n- Formal risk management process\n- Risk register\n- Specific risk assessment methodology\n- Documented risk assessments (unless organization decides to)\n\nHowever, many organizations do use tools like PFMEA to fulfill risk-based thinking requirements, especially in automotive (IATF 16949 requires it).\n</details>\n\n<details><summary>**Question 8**: Describe what management review is and what should be included in the inputs and outputs.</summary>\n\n**Answer:**\n\n**What is Management Review?**\n\nManagement review is a formal, periodic evaluation of the QMS by top management to:\n- Ensure continuing suitability (appropriate for the organization)\n- Ensure adequacy (sufficient to meet requirements)\n- Ensure effectiveness (achieving intended results)\n- Ensure alignment with strategic direction\n- Identify improvement opportunities\n\n**Frequency:** At least annually; many organizations conduct quarterly reviews\n\n**Required Inputs (ISO 9001 Clause 9.3.2):**\n\n| Input | What to Review |\n|-------|----------------|\n| Status of previous actions | Actions from prior reviews - completed? effective? |\n| Changes in external/internal issues | Market changes, regulations, technology, organizational changes |\n| QMS performance and effectiveness | Customer satisfaction, quality objectives, process performance, nonconformities, audit results, supplier performance |\n| Resource adequacy | People, infrastructure, environment, knowledge |\n| Effectiveness of risk actions | Did actions address risks/opportunities? |\n| Improvement opportunities | Suggestions, benchmarking, new technologies |\n\n**Required Outputs (ISO 9001 Clause 9.3.3):**\n\n| Output | Examples |\n|--------|----------|\n| Improvement decisions | Launch specific improvement projects, address recurring issues |\n| QMS changes | Revise quality objectives, update processes, modify documentation |\n| Resource needs | Budget approvals, hiring, equipment purchases, training |\n\n**Best Practices:**\n- Use a standard agenda aligned with required inputs\n- Prepare data in advance (dashboards, trend charts)\n- Document decisions and action items with owners and due dates\n- Follow up on action completion\n- Keep minutes as quality records\n\n**Evidence Required:**\n- Meeting minutes or management review report\n- Attendance record (top management participation)\n- Action items with status tracking\n- Data/reports presented\n</details>\n\n---\n\n## References\n\n1. ISO 9001:2015. *Quality Management Systems - Requirements*. International Organization for Standardization.\n\n2. ISO 9000:2015. *Quality Management Systems - Fundamentals and Vocabulary*. International Organization for Standardization.\n\n3. IATF 16949:2016. *Quality Management System Requirements for Automotive Production and Relevant Service Parts Organizations*. International Automotive Task Force.\n\n4. AS9100D:2016. *Quality Management Systems - Requirements for Aviation, Space and Defense Organizations*. SAE International.\n\n5. ISO 22000:2018. *Food Safety Management Systems - Requirements for Any Organization in the Food Chain*. International Organization for Standardization.\n\n6. ISO 19011:2018. *Guidelines for Auditing Management Systems*. International Organization for Standardization.\n\n7. Hoyle, D. (2017). *ISO 9000 Quality Systems Handbook* (7th ed.). Routledge.\n\n8. AIAG. (2010). *Advanced Product Quality Planning and Control Plan (APQP)* (2nd ed.). Automotive Industry Action Group.\n\n9. ASQ. (2019). *The Certified Quality Auditor Handbook* (4th ed.). ASQ Quality Press.\n\n10. Juran, J.M., & De Feo, J.A. (2010). *Juran's Quality Handbook* (6th ed.). McGraw-Hill.\n",
    "supporting": [
      "13-Quality-Systems_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}