{
  "hash": "425cc43cd7fc01e1e3e66dd9e0a42784",
  "result": {
    "engine": "knitr",
    "markdown": "# Process Failure Mode and Effects Analysis (PFMEA)\n\n------------------------------------------------------------------------\n\n\n## Learning Objectives\n\nBy the end of this chapter, you will be able to:\n\n- Explain the purpose and benefits of PFMEA in manufacturing\n- Distinguish between DFMEA (Design) and PFMEA (Process)\n- Apply the 10-step PFMEA methodology to a manufacturing process\n- Correctly rate Severity, Occurrence, and Detection using standardized scales\n- Calculate Risk Priority Numbers (RPN) and prioritize actions\n- Develop recommended actions to reduce process risks\n- Create and maintain PFMEA documentation as a living document\n\n> \"An ounce of prevention is worth a pound of cure.\"\n> — Benjamin Franklin\n\n------------------------------------------------------------------------\n\n## Introduction to PFMEA\n\n### What is PFMEA?\n\n**Process Failure Mode and Effects Analysis (PFMEA)** is a systematic, proactive method for evaluating a manufacturing or business process to identify where and how it might fail, and to assess the relative impact of different failures. The goal is to identify and prioritize actions that will prevent defects before they occur.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\ni Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![PFMEA: A Proactive Quality Tool](14-PFMEA_files/figure-pdf/pfmea-definition-1.pdf){fig-align='center'}\n:::\n:::\n\n\n### Brief History of FMEA\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{6em}ll}\n\\caption{\\label{tab:fmea-history}Evolution of FMEA}\\\\\n\\toprule\n\\cellcolor[HTML]{34495E}{\\textcolor{white}{\\textbf{Year}}} & \\cellcolor[HTML]{34495E}{\\textcolor{white}{\\textbf{Development}}} & \\cellcolor[HTML]{34495E}{\\textcolor{white}{\\textbf{Significance}}}\\\\\n\\midrule\n\\textbf{1949} & US Military develops FMEA (MIL-P-1629) & First formal FMEA methodology\\\\\n\\textbf{1960s} & NASA adopts FMEA for Apollo program & Proven reliability in life-critical systems\\\\\n\\textbf{1970s} & Automotive industry begins using FMEA & Ford, GM, Chrysler adoption drives standardization\\\\\n\\textbf{1980s} & AIAG publishes first FMEA manual & Industry-wide consistency established\\\\\n\\textbf{1990s} & QS-9000 requires FMEA for automotive suppliers & FMEA becomes mandatory in supply chain\\\\\n\\addlinespace\n\\textbf{2000s} & FMEA expands to healthcare, service industries & Methodology proves universal applicability\\\\\n\\textbf{2019} & AIAG-VDA FMEA Handbook published (current standard) & Harmonized global standard, introduces AP method\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### DFMEA vs. PFMEA\n\nTwo main types of FMEA are used in product development:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![DFMEA vs PFMEA: Different Focus, Same Methodology](14-PFMEA_files/figure-pdf/dfmea-pfmea-comparison-1.pdf){fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}>{}l>{}l}\n\\caption{\\label{tab:dfmea-pfmea-table}DFMEA vs PFMEA Comparison}\\\\\n\\toprule\n\\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Aspect}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{DFMEA (Design)}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{PFMEA (Process)}}}\\\\\n\\midrule\n\\textbf{**Primary Question**} & \\cellcolor[HTML]{D6EAF8}{Will the design meet requirements?} & \\cellcolor[HTML]{FADBD8}{Will the process produce conforming parts?}\\\\\n\\textbf{**Failure Mode Example**} & \\cellcolor[HTML]{D6EAF8}{Shaft diameter too small} & \\cellcolor[HTML]{FADBD8}{Shaft turned undersize}\\\\\n\\textbf{**Effect Example**} & \\cellcolor[HTML]{D6EAF8}{Premature bearing failure} & \\cellcolor[HTML]{FADBD8}{Part fails incoming inspection}\\\\\n\\textbf{**Cause Example**} & \\cellcolor[HTML]{D6EAF8}{Inadequate stress analysis} & \\cellcolor[HTML]{FADBD8}{Tool wear not monitored}\\\\\n\\textbf{**Control Example**} & \\cellcolor[HTML]{D6EAF8}{FEA simulation, prototype testing} & \\cellcolor[HTML]{FADBD8}{In-process gauging, SPC}\\\\\n\\addlinespace\n\\textbf{**Responsible Team**} & \\cellcolor[HTML]{D6EAF8}{Design engineering, R\\&D} & \\cellcolor[HTML]{FADBD8}{Manufacturing, quality, production}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n<details>\n<summary>Question: When should PFMEA be conducted?</summary>\n\n**Ideal Timing for PFMEA:**\n\n1. **New Process Development:** Before production begins, during process design\n2. **New Product Introduction:** When a new product will use existing processes\n3. **Process Changes:** Whenever significant changes are made to equipment, methods, or materials\n4. **Quality Issues:** When field failures or customer complaints indicate process problems\n5. **Regular Review:** Periodically (annually) to ensure continued relevance\n\n**Key Principle:** The earlier PFMEA is conducted, the lower the cost of implementing improvements. Changes during design cost 10x less than changes during production, and 100x less than changes after customer delivery.\n\n</details>\n\n### Why PFMEA Matters\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Benefits of PFMEA Implementation](14-PFMEA_files/figure-pdf/pfmea-benefits-1.pdf){fig-align='center'}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## PFMEA Fundamentals\n\n### Core Objectives\n\nThe fundamental objective of PFMEA is **prevention over detection** — identifying and eliminating potential failures before they occur, rather than finding defects after production.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}ll}\n\\caption{\\label{tab:pfmea-objectives}Core Objectives of PFMEA}\\\\\n\\toprule\n\\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Objective}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Description}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Outcome}}}\\\\\n\\midrule\n\\textbf{**Identify Failure Modes**} & Systematically identify all ways the process can fail & Comprehensive list of potential problems\\\\\n\\textbf{**Assess Risk**} & Evaluate severity, likelihood, and detectability of each failure & Quantified risk scores (RPN or AP)\\\\\n\\textbf{**Prioritize Actions**} & Focus resources on highest-risk failure modes & Action plan focused on critical issues\\\\\n\\textbf{**Document Knowledge**} & Capture institutional knowledge in a structured format & Living document for continuous improvement\\\\\n\\textbf{**Drive Improvement**} & Implement and verify effectiveness of countermeasures & Measurable reduction in process risk\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### The PFMEA Team\n\nPFMEA is most effective when conducted by a **cross-functional team**. No single person has all the knowledge needed to identify every potential failure.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![PFMEA Cross-Functional Team](14-PFMEA_files/figure-pdf/pfmea-team-1.pdf){fig-align='center'}\n:::\n:::\n\n\n<details>\n<summary>Question: Why is a cross-functional team essential?</summary>\n\n**A cross-functional team is essential because:**\n\n1. **Diverse Knowledge:** No single person understands all aspects of the process\n2. **Different Perspectives:** Quality sees defects, production sees constraints, maintenance sees failures\n3. **Buy-in:** People support what they help create\n4. **Historical Knowledge:** Operators often know about problems never formally documented\n5. **System Thinking:** Process interactions are visible when multiple functions participate\n\n**Common Mistake:** Having one engineer complete PFMEA alone as a \"paperwork exercise.\" This misses critical failure modes and produces an ineffective document.\n\n**Best Practice:** Minimum 4-6 team members, including at least one person with hands-on process experience.\n\n</details>\n\n### Key Terminology\n\nUnderstanding PFMEA terminology is essential for effective analysis:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{11}{13}\\selectfont\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}ll}\n\\caption{\\label{tab:pfmea-terminology}PFMEA Key Terminology}\\\\\n\\toprule\n\\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{Term}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{Definition}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{Example}}}\\\\\n\\midrule\n\\textbf{**Process Function**} & What the process step is supposed to do & 'Drill hole to 10mm ± 0.1mm'\\\\\n\\textbf{**Failure Mode**} & How the process can fail to perform its function & Hole diameter undersize, oversize, off-location\\\\\n\\textbf{**Failure Effect**} & The consequence of the failure on the customer or next operation & Part rejected at assembly, field failure\\\\\n\\textbf{**Severity (S)**} & Rating (1-10) of how serious the failure effect is & 10 = safety hazard, 1 = no effect\\\\\n\\textbf{**Failure Cause**} & Why the failure mode might occur & Drill bit wear, incorrect feed rate\\\\\n\\addlinespace\n\\textbf{**Occurrence (O)**} & Rating (1-10) of how likely the cause is to happen & 10 = very high, 1 = remote\\\\\n\\textbf{**Current Controls**} & What currently prevents the cause or detects the failure & In-process gauge, SPC chart\\\\\n\\textbf{**Detection (D)**} & Rating (1-10) of how likely current controls will detect the failure & 10 = no detection, 1 = certain detection\\\\\n\\textbf{**RPN**} & Risk Priority Number = S × O × D & Range: 1 to 1000\\\\\n\\textbf{**Action Priority (AP)**} & Alternative prioritization method (AIAG-VDA) & High, Medium, Low\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n### The PFMEA Form\n\nThe PFMEA is documented in a structured form. Here is a simplified template:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{10}{12}\\selectfont\n\n\\begin{longtable}[t]{lllllllllll}\n\\caption{\\label{tab:pfmea-form}PFMEA Form Template (Simplified)}\\\\\n\\toprule\n\\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Process Step}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Function}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Failure Mode}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Effect}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{S}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Cause}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{O}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Current Controls}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{D}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{RPN}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Action}}}\\\\\n\\midrule\n\\cellcolor[HTML]{D5F5E3}{Example:} & \\cellcolor[HTML]{D5F5E3}{Drill hole} & \\cellcolor[HTML]{D5F5E3}{Hole undersize} & \\cellcolor[HTML]{D5F5E3}{Assembly interference} & \\cellcolor[HTML]{D5F5E3}{7} & \\cellcolor[HTML]{D5F5E3}{Drill wear} & \\cellcolor[HTML]{D5F5E3}{5} & \\cellcolor[HTML]{D5F5E3}{Visual inspection} & \\cellcolor[HTML]{D5F5E3}{6} & \\cellcolor[HTML]{D5F5E3}{210} & \\cellcolor[HTML]{D5F5E3}{Add in-process gauge}\\\\\n &  &  &  &  &  &  &  &  &  & \\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## The PFMEA Methodology: 10 Steps\n\nPFMEA follows a systematic 10-step methodology. Each step builds on the previous one.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The 10-Step PFMEA Methodology](14-PFMEA_files/figure-pdf/pfmea-steps-overview-1.pdf){fig-align='center'}\n:::\n:::\n\n\n### Step 1: Define Scope and Process Boundaries\n\nBefore starting the analysis, clearly define what is included and excluded.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}ll}\n\\caption{\\label{tab:step1-scope}Step 1: Defining PFMEA Scope}\\\\\n\\toprule\n\\cellcolor[HTML]{3498DB}{\\textcolor{white}{\\textbf{Element}}} & \\cellcolor[HTML]{3498DB}{\\textcolor{white}{\\textbf{Description}}} & \\cellcolor[HTML]{3498DB}{\\textcolor{white}{\\textbf{Example: Injection Molding}}}\\\\\n\\midrule\n\\textbf{**Process Name**} & Clear name identifying the process & Plastic Part Injection Molding\\\\\n\\textbf{**Start Boundary**} & Where does our analysis begin? & Raw material loading into hopper\\\\\n\\textbf{**End Boundary**} & Where does our analysis end? & Part removed from mold, ready for packaging\\\\\n\\textbf{**Included Operations**} & All operations within scope & Material prep, injection, cooling, ejection, inspection\\\\\n\\textbf{**Excluded Operations**} & Operations analyzed separately or by others & Mold design (covered by DFMEA), packaging\\\\\n\\addlinespace\n\\textbf{**Key Assumptions**} & Conditions assumed to be true & Material meets incoming spec, mold is validated\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Step 2: Process Mapping and Identifying Functions\n\nCreate a detailed process flow diagram and identify the function of each step.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Example: Injection Molding Process Flow](14-PFMEA_files/figure-pdf/step2-process-map-1.pdf){fig-align='center'}\n:::\n:::\n\n\n### Step 3: Identifying Potential Failure Modes\n\nFor each process function, ask: **\"How can this step fail to perform its intended function?\"**\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{15em}l>{\\raggedright\\arraybackslash}p{10em}}\n\\caption{\\label{tab:step3-failure-modes}Step 3: Identifying Failure Modes}\\\\\n\\toprule\n\\cellcolor[HTML]{F39C12}{\\textcolor{white}{\\textbf{Process Function}}} & \\cellcolor[HTML]{F39C12}{\\textcolor{white}{\\textbf{Potential Failure Mode}}} & \\cellcolor[HTML]{F39C12}{\\textcolor{white}{\\textbf{Category}}}\\\\\n\\midrule\nLoad correct material & Wrong material loaded & \\cellcolor[HTML]{FEF9E7}{Wrong item}\\\\\nLoad correct material & Material contaminated & \\cellcolor[HTML]{FEF9E7}{Degraded item}\\\\\nLoad correct material & Insufficient material & \\cellcolor[HTML]{FEF9E7}{Missing item}\\\\\nMelt to specification temperature & Temperature too low & \\cellcolor[HTML]{FEF9E7}{Below specification}\\\\\nMelt to specification temperature & Temperature too high & \\cellcolor[HTML]{FEF9E7}{Above specification}\\\\\n\\addlinespace\nFill mold completely & Short shot (incomplete fill) & \\cellcolor[HTML]{FEF9E7}{Incomplete operation}\\\\\nFill mold completely & Flash (overfill) & \\cellcolor[HTML]{FEF9E7}{Excessive operation}\\\\\nFill mold completely & Air entrapment & \\cellcolor[HTML]{FEF9E7}{Unintended result}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n**Common failure mode categories:**\n- **No operation** (step doesn't happen)\n- **Partial operation** (incomplete)\n- **Degraded operation** (below standard)\n- **Excessive operation** (too much)\n- **Wrong operation** (incorrect action)\n- **Intermittent operation** (inconsistent)\n\n<details>\n<summary>Interactive Exercise: Identify Failure Modes</summary>\n\n**Process Step:** Heat treat steel parts at 850°C for 2 hours\n\n**Function:** Achieve required hardness (58-62 HRC)\n\n**Identify at least 5 potential failure modes:**\n\n**Answers:**\n1. Temperature too low → Parts soft (below hardness spec)\n2. Temperature too high → Parts brittle/cracked\n3. Time too short → Incomplete hardening\n4. Time too long → Over-hardening, distortion\n5. Uneven heating → Inconsistent hardness across part\n6. Wrong atmosphere → Surface decarburization\n7. Quench delay too long → Soft spots\n\n</details>\n\n### Step 4: Analyzing Failure Effects\n\nFor each failure mode, determine: **\"What is the consequence if this failure occurs?\"**\n\nConsider effects at multiple levels:\n1. **Local effect:** Impact on immediate operation\n2. **Next operation effect:** Impact on downstream process\n3. **End customer effect:** Impact on final user\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{lll}\n\\caption{\\label{tab:step4-effects}Step 4: Analyzing Effects at Multiple Levels}\\\\\n\\toprule\n\\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Failure Mode}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Effect Level}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Effect Description}}}\\\\\n\\midrule\nShort shot & Local & Part is incomplete/missing features\\\\\nShort shot & Next Operation & Part rejected at inspection, line stoppage\\\\\n\\cellcolor[HTML]{FADBD8}{Short shot} & \\cellcolor[HTML]{FADBD8}{End Customer} & \\cellcolor[HTML]{FADBD8}{If shipped: product malfunction, safety hazard}\\\\\nFlash & Local & Excess material on part edges\\\\\nFlash & Next Operation & Secondary trimming required, increased cycle time\\\\\n\\addlinespace\n\\cellcolor[HTML]{FADBD8}{Flash} & \\cellcolor[HTML]{FADBD8}{End Customer} & \\cellcolor[HTML]{FADBD8}{If shipped: poor fit, appearance defect}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Step 5: Determining Severity Ratings\n\n**Severity (S)** rates the seriousness of the effect on a scale of 1-10.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{11}{13}\\selectfont\n\n\\begin{longtable}[t]{>{\\raggedleft\\arraybackslash}p{5em}lll}\n\\caption{\\label{tab:severity-scale}Severity Rating Scale (S)}\\\\\n\\toprule\n\\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Rating}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Effect}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Criteria}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Example}}}\\\\\n\\midrule\n\\textbf{\\cellcolor[HTML]{FADBD8}{\\textbf{10}}} & \\cellcolor[HTML]{FADBD8}{\\textbf{Hazardous - without warning}} & \\cellcolor[HTML]{FADBD8}{\\textbf{Safety hazard; noncompliance with regulations; no warning}} & \\cellcolor[HTML]{FADBD8}{\\textbf{Brake failure without warning}}\\\\\n\\textbf{\\cellcolor[HTML]{FADBD8}{\\textbf{9}}} & \\cellcolor[HTML]{FADBD8}{\\textbf{Hazardous - with warning}} & \\cellcolor[HTML]{FADBD8}{\\textbf{Safety hazard; noncompliance with regulations; with warning}} & \\cellcolor[HTML]{FADBD8}{\\textbf{Airbag warning light before failure}}\\\\\n\\textbf{\\cellcolor[HTML]{FEF9E7}{8}} & \\cellcolor[HTML]{FEF9E7}{Very High} & \\cellcolor[HTML]{FEF9E7}{Product inoperable; loss of primary function} & \\cellcolor[HTML]{FEF9E7}{Engine won't start}\\\\\n\\textbf{\\cellcolor[HTML]{FEF9E7}{7}} & \\cellcolor[HTML]{FEF9E7}{High} & \\cellcolor[HTML]{FEF9E7}{Product operable but at reduced performance} & \\cellcolor[HTML]{FEF9E7}{Engine runs rough, reduced power}\\\\\n\\textbf{6} & Moderate & Product operable; comfort/convenience affected; noticeable & Wind noise, A/C takes longer to cool\\\\\n\\addlinespace\n\\textbf{5} & Low & Product operable; reduced comfort; noticed by average customer & Door handle feels loose\\\\\n\\textbf{4} & Very Low & Product operable; slightly reduced comfort; noticed by discriminating customer & Slight paint imperfection\\\\\n\\textbf{3} & Minor & Fit/finish nonconforming; noticed by discriminating customer & Panel gap slightly uneven\\\\\n\\textbf{2} & Very Minor & Fit/finish nonconforming; noticed only by trained observer & Under-hood label crooked\\\\\n\\textbf{1} & None & No discernible effect & No effect observable\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n> **Important:** Severity is determined by the **effect**, not the failure mode. Severity can only be reduced by changing the design — process changes typically cannot reduce severity.\n\n### Step 6: Identifying Potential Causes\n\nFor each failure mode, identify all possible causes: **\"Why might this failure occur?\"**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Fishbone Diagram: Causes of Short Shot](14-PFMEA_files/figure-pdf/step6-causes-1.pdf){fig-align='center'}\n:::\n:::\n\n\n### Step 7: Rating Occurrence\n\n**Occurrence (O)** rates the likelihood that the cause will occur on a scale of 1-10.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{11}{13}\\selectfont\n\n\\begin{longtable}[t]{>{\\raggedleft\\arraybackslash}p{5em}llll}\n\\caption{\\label{tab:occurrence-scale}Occurrence Rating Scale (O)}\\\\\n\\toprule\n\\cellcolor[HTML]{F39C12}{\\textcolor{white}{\\textbf{Rating}}} & \\cellcolor[HTML]{F39C12}{\\textcolor{white}{\\textbf{Likelihood}}} & \\cellcolor[HTML]{F39C12}{\\textcolor{white}{\\textbf{Criteria}}} & \\cellcolor[HTML]{F39C12}{\\textcolor{white}{\\textbf{Approximate Rate}}} & \\cellcolor[HTML]{F39C12}{\\textcolor{white}{\\textbf{Cpk Equivalent}}}\\\\\n\\midrule\n\\textbf{\\cellcolor[HTML]{FADBD8}{10}} & \\cellcolor[HTML]{FADBD8}{Very High} & \\cellcolor[HTML]{FADBD8}{Failure is almost inevitable} & \\cellcolor[HTML]{FADBD8}{≥100 per 1000 (≥10\\%)} & \\cellcolor[HTML]{FADBD8}{< 0.33}\\\\\n\\textbf{\\cellcolor[HTML]{FADBD8}{9}} & \\cellcolor[HTML]{FADBD8}{Very High} & \\cellcolor[HTML]{FADBD8}{Failures occur very frequently} & \\cellcolor[HTML]{FADBD8}{50 per 1000 (5\\%)} & \\cellcolor[HTML]{FADBD8}{≥ 0.33}\\\\\n\\textbf{\\cellcolor[HTML]{FEF9E7}{8}} & \\cellcolor[HTML]{FEF9E7}{High} & \\cellcolor[HTML]{FEF9E7}{Failures occur frequently} & \\cellcolor[HTML]{FEF9E7}{20 per 1000 (2\\%)} & \\cellcolor[HTML]{FEF9E7}{≥ 0.51}\\\\\n\\textbf{\\cellcolor[HTML]{FEF9E7}{7}} & \\cellcolor[HTML]{FEF9E7}{High} & \\cellcolor[HTML]{FEF9E7}{Failures occur on regular basis} & \\cellcolor[HTML]{FEF9E7}{10 per 1000 (1\\%)} & \\cellcolor[HTML]{FEF9E7}{≥ 0.67}\\\\\n\\textbf{6} & Moderate & Occasional failures & 5 per 1000 (0.5\\%) & ≥ 0.83\\\\\n\\addlinespace\n\\textbf{5} & Moderate & Occasional failures expected & 2 per 1000 (0.2\\%) & ≥ 1.00\\\\\n\\textbf{4} & Low & Relatively few failures & 1 per 1000 (0.1\\%) & ≥ 1.17\\\\\n\\textbf{3} & Low & Few failures & 0.5 per 1000 (500 ppm) & ≥ 1.33\\\\\n\\textbf{2} & Remote & Failure unlikely & 0.1 per 1000 (100 ppm) & ≥ 1.50\\\\\n\\textbf{1} & Remote & Failure nearly impossible & ≤0.01 per 1000 (≤10 ppm) & ≥ 1.67\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n### Step 8: Current Controls and Detection Ratings\n\nIdentify current controls and rate their ability to detect the failure or cause.\n\n**Types of Process Controls:**\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}lll}\n\\caption{\\label{tab:control-types}Types of Process Controls}\\\\\n\\toprule\n\\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Control Type}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Purpose}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Examples}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Impact on PFMEA}}}\\\\\n\\midrule\n\\textbf{**Prevention Controls**} & Prevent the cause from occurring & Error-proofing (poka-yoke), interlocks, maintenance programs & Reduces Occurrence rating\\\\\n\\textbf{**Detection Controls**} & Detect the failure mode or cause after it occurs & Inspection, testing, gauging, SPC monitoring & Reduces Detection rating\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n**Detection Rating Scale:**\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{11}{13}\\selectfont\n\n\\begin{longtable}[t]{>{\\raggedleft\\arraybackslash}p{5em}lll}\n\\caption{\\label{tab:detection-scale}Detection Rating Scale (D)}\\\\\n\\toprule\n\\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Rating}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Detection}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Criteria}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Example Control}}}\\\\\n\\midrule\n\\textbf{\\cellcolor[HTML]{FADBD8}{10}} & \\cellcolor[HTML]{FADBD8}{Absolute Uncertainty} & \\cellcolor[HTML]{FADBD8}{No current control; cannot detect or is not analyzed} & \\cellcolor[HTML]{FADBD8}{No inspection planned}\\\\\n\\textbf{\\cellcolor[HTML]{FADBD8}{9}} & \\cellcolor[HTML]{FADBD8}{Very Remote} & \\cellcolor[HTML]{FADBD8}{Control will probably not detect} & \\cellcolor[HTML]{FADBD8}{Indirect measurement only}\\\\\n\\textbf{\\cellcolor[HTML]{FADBD8}{8}} & \\cellcolor[HTML]{FADBD8}{Remote} & \\cellcolor[HTML]{FADBD8}{Control has poor chance of detection} & \\cellcolor[HTML]{FADBD8}{Visual inspection of hidden feature}\\\\\n\\textbf{7} & Very Low & Control has low chance of detection & Manual 100\\% visual inspection\\\\\n\\textbf{6} & Low & Control may detect & Variable gauging after operation\\\\\n\\addlinespace\n\\textbf{5} & Moderate & Control has moderate chance of detection & SPC charting\\\\\n\\textbf{4} & Moderately High & Control has moderately high chance of detection & In-station gauging with feedback\\\\\n\\textbf{3} & High & Control has high chance of detection & Automated 100\\% gauging\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{2}} & \\cellcolor[HTML]{D5F5E3}{Very High} & \\cellcolor[HTML]{D5F5E3}{Control almost certain to detect} & \\cellcolor[HTML]{D5F5E3}{Multiple independent automated checks}\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{1}} & \\cellcolor[HTML]{D5F5E3}{Almost Certain} & \\cellcolor[HTML]{D5F5E3}{Control will detect; error-proofed} & \\cellcolor[HTML]{D5F5E3}{Error-proofing prevents defect creation}\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n> **Important:** Detection ratings are often **harder to reduce** than occurrence ratings. Adding inspection doesn't prevent defects — it only catches them. Prevention is always better than detection.\n\n<details>\n<summary>Question: Why are detection ratings often harder to improve?</summary>\n\n**Detection ratings are harder to reduce because:**\n\n1. **Detection doesn't prevent:** The defect has already been made; you're just trying to find it\n2. **Human inspection is unreliable:** Typical effectiveness is only 80-85% for visual inspection\n3. **100% inspection is expensive:** Automated inspection requires significant investment\n4. **Some defects are hard to detect:** Internal defects, intermittent problems, latent failures\n5. **Sampling has limitations:** Even good sampling plans miss some defects\n\n**Better approach:** Focus on reducing occurrence through:\n- Error-proofing (poka-yoke)\n- Process capability improvement\n- Preventive maintenance\n- Better training\n\n</details>\n\n### Step 9: Calculating RPN and Prioritization\n\nThe **Risk Priority Number (RPN)** combines all three ratings:\n\n$$\\text{RPN} = \\text{Severity (S)} \\times \\text{Occurrence (O)} \\times \\text{Detection (D)}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Example RPN Calculations\n\n# Failure Mode 1: Short shot\nS1 <- 7    # Severity: Product inoperable (assembly)\nO1 <- 5    # Occurrence: Occasional\nD1 <- 6    # Detection: Moderate (visual inspection)\n\nRPN1 <- S1 * O1 * D1\ncat(\"Short shot RPN:\", RPN1, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nShort shot RPN: 210 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Failure Mode 2: Flash\nS2 <- 4    # Severity: Appearance issue\nO2 <- 6    # Occurrence: Regular\nD2 <- 3    # Detection: High (easy to see)\n\nRPN2 <- S2 * O2 * D2\ncat(\"Flash RPN:\", RPN2, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFlash RPN: 72 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Failure Mode 3: Contamination\nS3 <- 9    # Severity: Safety concern (medical device)\nO3 <- 3    # Occurrence: Low\nD3 <- 7    # Detection: Low (internal contamination)\n\nRPN3 <- S3 * O3 * D3\ncat(\"Contamination RPN:\", RPN3, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nContamination RPN: 189 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Comparison\ncat(\"\\n--- Priority Order by RPN ---\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- Priority Order by RPN ---\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"1. Short shot (RPN =\", RPN1, \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n1. Short shot (RPN = 210 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"2. Contamination (RPN =\", RPN3, \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n2. Contamination (RPN = 189 )\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"3. Flash (RPN =\", RPN2, \")\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3. Flash (RPN = 72 )\n```\n\n\n:::\n:::\n\n\n**RPN Action Thresholds (Traditional):**\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{lll}\n\\caption{\\label{tab:rpn-thresholds}RPN Action Thresholds}\\\\\n\\toprule\n\\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{RPN Range}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Risk Level}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Action Required}}}\\\\\n\\midrule\n\\cellcolor[HTML]{D5F5E3}{1-50} & \\cellcolor[HTML]{D5F5E3}{Low} & \\cellcolor[HTML]{D5F5E3}{Monitor; no immediate action}\\\\\n\\cellcolor[HTML]{D5F5E3}{51-100} & \\cellcolor[HTML]{D5F5E3}{Moderate} & \\cellcolor[HTML]{D5F5E3}{Consider action if resources available}\\\\\n\\cellcolor[HTML]{FEF9E7}{101-200} & \\cellcolor[HTML]{FEF9E7}{Significant} & \\cellcolor[HTML]{FEF9E7}{Action required within planning cycle}\\\\\n\\cellcolor[HTML]{FADBD8}{201-500} & \\cellcolor[HTML]{FADBD8}{High} & \\cellcolor[HTML]{FADBD8}{Immediate action required}\\\\\n\\cellcolor[HTML]{E74C3C}{\\textcolor{white}{501-1000}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{Critical}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{Stop production; immediate corrective action}}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n<details>\n<summary>Interactive Exercise: Calculate RPN</summary>\n\n**Calculate the RPN for each failure mode and rank them:**\n\n| Failure Mode | Severity | Occurrence | Detection | RPN |\n|--------------|----------|------------|-----------|-----|\n| A: Dimension out of spec | 6 | 4 | 5 | ? |\n| B: Surface scratch | 3 | 7 | 2 | ? |\n| C: Missing component | 8 | 2 | 8 | ? |\n| D: Wrong material | 9 | 3 | 6 | ? |\n\n**Answers:**\n- A: 6 × 4 × 5 = **120**\n- B: 3 × 7 × 2 = **42**\n- C: 8 × 2 × 8 = **128**\n- D: 9 × 3 × 6 = **162**\n\n**Priority Order:** D (162) > C (128) > A (120) > B (42)\n\n**Question:** Should we always address the highest RPN first? See limitations discussion below.\n\n</details>\n\n### Limitations of RPN\n\nRPN has known limitations that must be understood:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![RPN Limitation Example](14-PFMEA_files/figure-pdf/rpn-limitations-1.pdf){fig-align='center'}\n:::\n:::\n\n\n**Key RPN Limitations:**\n\n1. **Same RPN, different risk:** 10×1×4 = 40, but 2×10×2 = 40\n2. **Severity often overlooked:** High severity should always trigger action\n3. **Arbitrary thresholds:** Why is 100 the magic number?\n4. **Non-linear scale:** Difference between 2 and 3 is not same as 8 and 9\n\n### Action Priority (AP) Method — AIAG-VDA Alternative\n\nThe 2019 AIAG-VDA FMEA Handbook introduced the **Action Priority (AP)** method as an alternative to RPN.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{8em}ll}\n\\caption{\\label{tab:ap-method}Action Priority (AP) Method}\\\\\n\\toprule\n\\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{Priority}}} & \\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{Criteria}}} & \\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{Action Required}}}\\\\\n\\midrule\n\\textbf{\\cellcolor[HTML]{FADBD8}{**HIGH**}} & \\cellcolor[HTML]{FADBD8}{Severity = 9 or 10 (any O, any D)} & \\cellcolor[HTML]{FADBD8}{Must take action to improve prevention/detection}\\\\\n\\textbf{\\cellcolor[HTML]{FADBD8}{**HIGH**}} & \\cellcolor[HTML]{FADBD8}{Severity = 8 AND Occurrence ≥ 4} & \\cellcolor[HTML]{FADBD8}{Must take action}\\\\\n\\textbf{\\cellcolor[HTML]{FEF9E7}{**MEDIUM**}} & \\cellcolor[HTML]{FEF9E7}{Severity = 7 AND Occurrence ≥ 5} & \\cellcolor[HTML]{FEF9E7}{Should take action}\\\\\n\\textbf{\\cellcolor[HTML]{FEF9E7}{**MEDIUM**}} & \\cellcolor[HTML]{FEF9E7}{Severity = 5-6 AND Occurrence ≥ 6 AND Detection ≥ 5} & \\cellcolor[HTML]{FEF9E7}{Should take action}\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{**LOW**}} & \\cellcolor[HTML]{D5F5E3}{All other combinations} & \\cellcolor[HTML]{D5F5E3}{May take action; document rationale if no action}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Step 10: Recommended Actions and Follow-Up\n\nFor high-priority items, develop specific recommended actions.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{10}{12}\\selectfont\n\n\\begin{longtable}[t]{l>{}rlllrrr>{}r}\n\\caption{\\label{tab:recommended-actions}Step 10: Recommended Actions with Targets}\\\\\n\\toprule\n\\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Failure Mode}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Current RPN}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Recommended Action}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Responsible}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Target Date}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Target S}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Target O}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Target D}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Target RPN}}}\\\\\n\\midrule\nShort shot & \\textbf{210} & Install shot size monitoring with automatic reject & Process Engineer & 2024-03-15 & 7 & 3 & 2 & \\textbf{42}\\\\\nShort shot & \\textbf{210} & Implement preventive maintenance for nozzle cleaning & Maintenance & 2024-02-28 & 7 & 2 & 6 & \\textbf{84}\\\\\nShort shot & \\textbf{210} & Add mold temperature monitoring with alarm & Quality Engineer & 2024-03-01 & 7 & 5 & 4 & \\textbf{140}\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Complete PFMEA Example: Injection Molding\n\nLet's work through a complete PFMEA for an injection molding process step by step.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{10}{12}\\selectfont\n\n\\begin{longtable}[t]{llllrlrlr>{}r}\n\\caption{\\label{tab:complete-example}Complete PFMEA Example: Injection Molding Process}\\\\\n\\toprule\n\\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Step}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Function}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Failure Mode}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Effect}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{S}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Cause}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{O}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Control}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{D}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{RPN}}}\\\\\n\\midrule\n\\cellcolor[HTML]{FADBD8}{3. Inject} & \\cellcolor[HTML]{FADBD8}{Fill mold completely} & \\cellcolor[HTML]{FADBD8}{Short shot} & \\cellcolor[HTML]{FADBD8}{Part scrapped, line stoppage} & \\cellcolor[HTML]{FADBD8}{7} & \\cellcolor[HTML]{FADBD8}{Insufficient shot size} & \\cellcolor[HTML]{FADBD8}{5} & \\cellcolor[HTML]{FADBD8}{Visual inspection} & \\cellcolor[HTML]{FADBD8}{6} & \\textbf{\\cellcolor[HTML]{FADBD8}{210}}\\\\\n3. Inject & Fill mold completely & Flash & Secondary trim required & 4 & Excessive pressure & 6 & Visual inspection & 3 & \\textbf{72}\\\\\n3. Inject & Fill mold completely & Air entrapment & Weak area, visual defect & 6 & Blocked vent & 4 & First article inspection & 5 & \\textbf{120}\\\\\n4. Cool & Solidify uniformly & Warpage & Dimensional rejection & 7 & Uneven cooling & 4 & CMM sample check & 4 & \\textbf{112}\\\\\n4. Cool & Solidify uniformly & Sink marks & Visual defect & 5 & Thick section, short pack & 5 & Visual inspection & 4 & \\textbf{100}\\\\\n\\addlinespace\n5. Eject & Remove without damage & Stuck in mold & Part damage, mold damage & 8 & Insufficient draft angle & 3 & Ejector pressure monitor & 5 & \\textbf{120}\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Improvement Analysis for Short Shot (Highest RPN = 210)\n\ncat(\"=== CURRENT STATE ===\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== CURRENT STATE ===\n```\n\n\n:::\n\n```{.r .cell-code}\nS_current <- 7  # Severity (cannot change - inherent to failure)\nO_current <- 5  # Occurrence\nD_current <- 6  # Detection\nRPN_current <- S_current * O_current * D_current\ncat(\"Current RPN:\", RPN_current, \"(S=7, O=5, D=6)\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCurrent RPN: 210 (S=7, O=5, D=6)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"=== IMPROVEMENT OPTIONS ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== IMPROVEMENT OPTIONS ===\n```\n\n\n:::\n\n```{.r .cell-code}\n# Option 1: Improve Detection\ncat(\"Option 1: Add automatic shot weight monitoring\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOption 1: Add automatic shot weight monitoring\n```\n\n\n:::\n\n```{.r .cell-code}\nD_option1 <- 2  # Automated detection\nRPN_option1 <- S_current * O_current * D_option1\ncat(\"New RPN:\", RPN_option1, \"(S=7, O=5, D=2)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNew RPN: 70 (S=7, O=5, D=2)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reduction:\", round((1 - RPN_option1/RPN_current)*100), \"%\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReduction: 67 %\n```\n\n\n:::\n\n```{.r .cell-code}\n# Option 2: Improve Occurrence (Prevention)\ncat(\"Option 2: Add screw position monitoring with feedback control\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOption 2: Add screw position monitoring with feedback control\n```\n\n\n:::\n\n```{.r .cell-code}\nO_option2 <- 2  # Much lower occurrence\nRPN_option2 <- S_current * O_option2 * D_current\ncat(\"New RPN:\", RPN_option2, \"(S=7, O=2, D=6)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNew RPN: 84 (S=7, O=2, D=6)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reduction:\", round((1 - RPN_option2/RPN_current)*100), \"%\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReduction: 60 %\n```\n\n\n:::\n\n```{.r .cell-code}\n# Option 3: Both improvements\ncat(\"Option 3: Both improvements combined\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOption 3: Both improvements combined\n```\n\n\n:::\n\n```{.r .cell-code}\nRPN_option3 <- S_current * O_option2 * D_option1\ncat(\"New RPN:\", RPN_option3, \"(S=7, O=2, D=2)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNew RPN: 28 (S=7, O=2, D=2)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reduction:\", round((1 - RPN_option3/RPN_current)*100), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReduction: 87 %\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![RPN Improvement Comparison](14-PFMEA_files/figure-pdf/rpn-comparison-viz-1.pdf){fig-align='center'}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Industry-Specific PFMEA Examples\n\n### Example: Welding Process\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{11}{13}\\selectfont\n\n\\begin{longtable}[t]{llrlrlrr}\n\\caption{\\label{tab:welding-pfmea}PFMEA Example: Welding Process}\\\\\n\\toprule\n\\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{Failure Mode}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{Effect}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{S}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{Cause}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{O}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{Current Control}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{D}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{RPN}}}\\\\\n\\midrule\nIncomplete fusion & Weak joint, potential crack & 9 & Low heat input, contamination & 4 & Visual + X-ray sample & 4 & 144\\\\\n\\cellcolor[HTML]{FADBD8}{Porosity} & \\cellcolor[HTML]{FADBD8}{Leak path, strength reduction} & \\cellcolor[HTML]{FADBD8}{8} & \\cellcolor[HTML]{FADBD8}{Shielding gas issue, moisture} & \\cellcolor[HTML]{FADBD8}{5} & \\cellcolor[HTML]{FADBD8}{Visual inspection} & \\cellcolor[HTML]{FADBD8}{5} & \\cellcolor[HTML]{FADBD8}{200}\\\\\nUndercut & Stress concentration, fatigue failure & 7 & Excessive current, wrong angle & 4 & Visual inspection & 4 & 112\\\\\nSpatter & Appearance, cleanup required & 3 & Wrong parameters, contaminated wire & 6 & Visual inspection & 2 & 36\\\\\nDistortion & Dimensional non-conformance & 6 & Excessive heat, improper sequence & 4 & CMM check & 5 & 120\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n### Example: Heat Treatment Process\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{11}{13}\\selectfont\n\n\\begin{longtable}[t]{llrlrlrr}\n\\caption{\\label{tab:heat-treat-pfmea}PFMEA Example: Heat Treatment Process}\\\\\n\\toprule\n\\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{Failure Mode}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{Effect}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{S}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{Cause}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{O}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{Current Control}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{D}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{RPN}}}\\\\\n\\midrule\nUnder-hardened & Premature wear, field failure & 8 & Low temp, short time & 4 & Hardness test sample & 4 & 128\\\\\nOver-hardened/Brittle & Part cracks under load & 9 & High temp, long time & 3 & Hardness test sample & 4 & 108\\\\\n\\cellcolor[HTML]{FADBD8}{Surface decarburization} & \\cellcolor[HTML]{FADBD8}{Soft surface, wear} & \\cellcolor[HTML]{FADBD8}{7} & \\cellcolor[HTML]{FADBD8}{Wrong atmosphere} & \\cellcolor[HTML]{FADBD8}{4} & \\cellcolor[HTML]{FADBD8}{Surface hardness check} & \\cellcolor[HTML]{FADBD8}{5} & \\cellcolor[HTML]{FADBD8}{140}\\\\\nDistortion/Warpage & Dimensional rejection & 6 & Uneven heating, rapid quench & 5 & CMM sample & 4 & 120\\\\\nQuench cracking & Scrap, safety hazard & 10 & Thermal shock, design & 2 & Visual inspection & 6 & 120\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n### Example: Food Processing (Pasteurization)\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{11}{13}\\selectfont\n\n\\begin{longtable}[t]{llrlrlrr}\n\\caption{\\label{tab:food-pfmea}PFMEA Example: Pasteurization Process}\\\\\n\\toprule\n\\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Failure Mode}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Effect}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{S}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Cause}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{O}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Current Control}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{D}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{RPN}}}\\\\\n\\midrule\n\\cellcolor[HTML]{FEF9E7}{Under-processing} & \\cellcolor[HTML]{FEF9E7}{Pathogen survival, food safety} & \\cellcolor[HTML]{FEF9E7}{10} & \\cellcolor[HTML]{FEF9E7}{Equipment malfunction, calibration} & \\cellcolor[HTML]{FEF9E7}{2} & \\cellcolor[HTML]{FEF9E7}{Continuous temp monitoring + chart recorder} & \\cellcolor[HTML]{FEF9E7}{2} & \\cellcolor[HTML]{FEF9E7}{40}\\\\\nOver-processing & Nutrient loss, off-flavor & 5 & Control system error & 3 & Temperature alarm & 3 & 45\\\\\nTemperature deviation & Inconsistent kill, shelf life & 8 & Sensor drift, flow variation & 3 & Calibration schedule & 3 & 72\\\\\nTime deviation & Process variation & 6 & Timer malfunction & 3 & Time verification & 3 & 54\\\\\n\\cellcolor[HTML]{FEF9E7}{Cross-contamination} & \\cellcolor[HTML]{FEF9E7}{Product recall, illness} & \\cellcolor[HTML]{FEF9E7}{10} & \\cellcolor[HTML]{FEF9E7}{Gasket leak, CIP failure} & \\cellcolor[HTML]{FEF9E7}{2} & \\cellcolor[HTML]{FEF9E7}{CIP verification + testing} & \\cellcolor[HTML]{FEF9E7}{4} & \\cellcolor[HTML]{FEF9E7}{80}\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n<details>\n<summary>Interactive Exercise: Create a PFMEA</summary>\n\n**Create a simple PFMEA for a coffee brewing process in a commercial setting.**\n\n**Process Steps:**\n1. Fill water reservoir\n2. Load coffee grounds\n3. Brew coffee\n4. Dispense into cup\n\n**Identify at least 4 failure modes with S, O, D ratings and RPN.**\n\n**Example Answer:**\n\n| Step | Failure Mode | Effect | S | Cause | O | Control | D | RPN |\n|------|--------------|--------|---|-------|---|---------|---|-----|\n| 1. Fill water | Wrong water level | Weak/strong coffee | 4 | No level indicator | 5 | Visual check | 5 | 100 |\n| 2. Load grounds | Wrong amount | Weak/strong coffee | 4 | No measuring | 6 | Visual check | 6 | 144 |\n| 3. Brew | Temperature too low | Under-extracted | 6 | Heating element worn | 3 | Temp display | 4 | 72 |\n| 4. Dispense | Overflow | Burn hazard, mess | 8 | Cup sensor failure | 2 | Cup sensor | 4 | 64 |\n\n**Priority:** Wrong amount (144) > Water level (100) > Temperature (72) > Overflow (64)\n\n</details>\n\n------------------------------------------------------------------------\n\n## Integration with Other Quality Tools\n\nPFMEA doesn't exist in isolation — it connects to other quality tools and systems.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![PFMEA Integration with Quality Tools](14-PFMEA_files/figure-pdf/integration-diagram-1.pdf){fig-align='center'}\n:::\n:::\n\n\n### From PFMEA to Control Plan\n\nThe PFMEA directly feeds the **Control Plan** — a document that specifies what controls are needed at each process step.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{ll}\n\\caption{\\label{tab:control-plan-link}PFMEA to Control Plan Linkage}\\\\\n\\toprule\n\\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{From PFMEA}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{To Control Plan}}}\\\\\n\\midrule\nProcess Step & Operation/Step\\\\\nFailure Mode & Characteristic to Control\\\\\nSeverity & Classification (Critical/Significant)\\\\\nCause & Process Parameter\\\\\nCurrent Control & Control Method\\\\\n\\addlinespace\nDetection & Reaction Plan\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Common Pitfalls and Best Practices\n\n### Common Pitfalls to Avoid\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}>{}ll}\n\\caption{\\label{tab:pitfalls}Common PFMEA Pitfalls and Solutions}\\\\\n\\toprule\n\\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Pitfall}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Problem}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Solution}}}\\\\\n\\midrule\n\\textbf{**Paperwork Exercise**} & \\cellcolor[HTML]{FADBD8}{PFMEA done only to satisfy customer requirement} & Conduct meaningful analysis with intent to improve\\\\\n\\textbf{**One-Person Show**} & \\cellcolor[HTML]{FADBD8}{Engineer completes alone without team input} & Require cross-functional team participation\\\\\n\\textbf{**Optimistic Detection**} & \\cellcolor[HTML]{FADBD8}{Overestimating effectiveness of current controls} & Validate detection effectiveness with data\\\\\n\\textbf{**Static Document**} & \\cellcolor[HTML]{FADBD8}{Never updated after process changes} & Review and update after any process change\\\\\n\\textbf{**RPN Obsession**} & \\cellcolor[HTML]{FADBD8}{Focusing only on RPN numbers, missing high-severity items} & Also consider severity alone; use AP method\\\\\n\\addlinespace\n\\textbf{**Vague Failure Modes**} & \\cellcolor[HTML]{FADBD8}{Failure modes too general to be actionable} & Be specific: 'hole undersize' not 'bad hole'\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Best Practices\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}l}\n\\caption{\\label{tab:best-practices}PFMEA Best Practices}\\\\\n\\toprule\n\\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Practice}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Description}}}\\\\\n\\midrule\n\\textbf{**Start Early**} & Begin PFMEA during process design, not after problems occur\\\\\n\\textbf{**Include Operators**} & Operators know failures that never get documented\\\\\n\\textbf{**Use Historical Data**} & Use warranty data, scrap reports, customer complaints\\\\\n\\textbf{**Be Specific**} & Specific failure modes lead to specific actions\\\\\n\\textbf{**Follow Up**} & Verify that actions were implemented and effective\\\\\n\\addlinespace\n\\textbf{**Living Document**} & Review and update regularly (minimum annually)\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Case Study: Preventing a Major Quality Issue\n\n### Background\n\n**Company:** Automotive brake component manufacturer\n\n**Product:** Brake caliper mounting bracket\n\n**Situation:** New manufacturing process being implemented for a high-volume contract\n\n### PFMEA Analysis\n\nDuring the PFMEA session, the team identified a critical failure mode:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{ll}\n\\caption{\\label{tab:case-study-finding}Case Study: Critical Failure Mode Identified}\\\\\n\\toprule\n\\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Element}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Analysis}}}\\\\\n\\midrule\nProcess Step & Drill mounting holes\\\\\nFunction & Create holes at 45.0 ±0.1mm spacing\\\\\nFailure Mode & Hole spacing out of tolerance\\\\\nEffect & Caliper misalignment, brake performance affected\\\\\n\\cellcolor[HTML]{FADBD8}{\\textbf{Severity}} & \\cellcolor[HTML]{FADBD8}{\\textbf{9 (safety-related)}}\\\\\n\\addlinespace\nCause & Fixture wear, thermal expansion\\\\\nOccurrence & 4 (occasional)\\\\\nCurrent Control & CMM check 5 per shift\\\\\nDetection & 5 (moderate sampling)\\\\\n\\cellcolor[HTML]{FADBD8}{\\textbf{RPN}} & \\cellcolor[HTML]{FADBD8}{\\textbf{180}}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Actions Taken\n\nBased on the PFMEA, the team implemented:\n\n1. **In-process gauging:** Automated measurement after every part (D: 5 → 2)\n2. **Fixture monitoring:** Temperature compensation and wear tracking (O: 4 → 2)\n3. **Enhanced fixture design:** Carbide wear surfaces (O: 4 → 2)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Before improvements\nS_before <- 9\nO_before <- 4\nD_before <- 5\nRPN_before <- S_before * O_before * D_before\ncat(\"Before RPN:\", RPN_before, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBefore RPN: 180 \n```\n\n\n:::\n\n```{.r .cell-code}\n# After improvements\nS_after <- 9    # Severity unchanged (inherent)\nO_after <- 2    # Reduced through fixture improvements\nD_after <- 2    # Reduced through 100% gauging\nRPN_after <- S_after * O_after * D_after\ncat(\"After RPN:\", RPN_after, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAfter RPN: 36 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Reduction:\", round((1 - RPN_after/RPN_before)*100), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReduction: 80 %\n```\n\n\n:::\n:::\n\n\n### Results\n\n- **Zero field failures** related to hole spacing after 18 months of production\n- **Estimated avoided cost:** $2.4 million in potential recall and warranty\n- **Investment:** $85,000 for gauging and fixture upgrades\n- **ROI:** 28:1\n\n> **Key Lesson:** The PFMEA investment of $85,000 prevented a potential $2.4 million problem. This is the power of proactive risk management.\n\n------------------------------------------------------------------------\n\n## Summary\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}l}\n\\caption{\\label{tab:summary-table-ch8}PFMEA Key Concepts Summary}\\\\\n\\toprule\n\\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Topic}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Key Points}}}\\\\\n\\midrule\n**PFMEA Purpose** & Prevent defects before they occur; proactive vs. reactive quality\\\\\n**Key Ratings** & Severity (effect), Occurrence (likelihood), Detection (control effectiveness)\\\\\n**RPN Calculation** & RPN = S × O × D; Range 1-1000; Higher = More risk\\\\\n**Prioritization** & Address high RPN first, but always act on high severity (9-10)\\\\\n**Action Priority** & AIAG-VDA method: High/Medium/Low based on S-O-D combination\\\\\n\\addlinespace\n**Best Practice** & Cross-functional team, living document, follow-up on actions\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Review Questions\n\n### Conceptual Questions\n\n<details>\n<summary>Question 1: What is the difference between a failure mode and a failure effect?</summary>\n\n**Failure Mode:** How the process fails to perform its intended function\n- Example: \"Hole drilled undersize\"\n- Example: \"Temperature too low\"\n- Example: \"Missing component\"\n\n**Failure Effect:** The consequence of the failure mode\n- Example: \"Part rejected at assembly\" (effect of undersize hole)\n- Example: \"Product not properly cured\" (effect of low temperature)\n- Example: \"Product doesn't function\" (effect of missing component)\n\n**Key Relationship:** One failure mode can have multiple effects at different levels (local, downstream, customer).\n\n</details>\n\n<details>\n<summary>Question 2: Why should PFMEA be conducted by a cross-functional team?</summary>\n\n**Reasons for Cross-Functional Team:**\n\n1. **Diverse expertise:** No single person understands all aspects\n2. **Multiple perspectives:** Quality sees defects differently than production\n3. **Historical knowledge:** Operators know undocumented problems\n4. **Buy-in:** People support what they help create\n5. **System thinking:** Process interactions become visible\n6. **Better solutions:** Different functions propose different improvements\n\n**Typical team composition:**\n- Process Engineer (owner)\n- Quality Engineer\n- Production Supervisor/Operator\n- Maintenance Technician\n- Design Engineer\n- Supplier Representative (when applicable)\n\n</details>\n\n<details>\n<summary>Question 3: Explain why detection ratings are often harder to reduce than occurrence ratings.</summary>\n\n**Detection is harder to reduce because:**\n\n1. **Detection doesn't prevent:** Defect already exists; just trying to find it\n2. **Human inspection is unreliable:** 80-85% effectiveness typical\n3. **100% inspection is expensive:** Requires automation investment\n4. **Some defects are hidden:** Internal defects, intermittent failures\n5. **Sampling limitations:** Cannot catch all defects with sampling\n\n**Better approach:** Focus on occurrence reduction:\n- Error-proofing (poka-yoke)\n- Process capability improvement\n- Preventive maintenance\n- Better training\n\n**Example:** Reducing drill wear (occurrence) is more effective than adding more inspection (detection).\n\n</details>\n\n<details>\n<summary>Question 4: At what point in process development should PFMEA ideally be conducted?</summary>\n\n**Ideal Timing:** During process design, before production begins\n\n**Why early is better:**\n- Changes cost 1x during design\n- Changes cost 10x during production\n- Changes cost 100x after customer delivery\n\n**PFMEA Timing Points:**\n1. **New process development:** Before equipment is ordered\n2. **New product introduction:** During process planning\n3. **Process changes:** Before implementing changes\n4. **Quality issues:** When problems indicate process risk\n5. **Regular review:** Annually at minimum\n\n**Key Principle:** The earlier PFMEA is conducted, the more opportunity exists to design out failures rather than inspect them out.\n\n</details>\n\n### Calculation Questions\n\n<details>\n<summary>Question 5: Given S=8, O=6, D=4, calculate RPN. If improved controls reduce detection to 2, what is the new RPN?</summary>\n\n**Initial Calculation:**\n```\nRPN = S × O × D\nRPN = 8 × 6 × 4 = 192\n```\n\n**After Detection Improvement:**\n```\nNew RPN = 8 × 6 × 2 = 96\n```\n\n**Analysis:**\n- Original RPN: 192 (Significant risk, action required)\n- New RPN: 96 (Moderate risk)\n- Reduction: 50%\n\n**Note:** Severity (8) remains unchanged because it's determined by the effect, not by process controls. Only occurrence and detection can be reduced through process improvements.\n\n</details>\n\n<details>\n<summary>Question 6: Two failure modes have RPNs of 120 and 150. Should the higher RPN always be addressed first?</summary>\n\n**Answer:** Not necessarily!\n\n**Consider the following scenarios:**\n\n**Scenario A:**\n- Failure Mode 1: RPN = 150 (S=3, O=10, D=5) — Minor cosmetic issue\n- Failure Mode 2: RPN = 120 (S=10, O=3, D=4) — Safety hazard\n\n**Priority:** Address Failure Mode 2 first despite lower RPN because:\n- Severity 10 indicates safety hazard\n- High-severity items should always be addressed regardless of RPN\n- The AP (Action Priority) method would classify this as HIGH priority\n\n**When to prioritize lower RPN:**\n- Higher severity (especially 9-10)\n- Regulatory or safety implications\n- Customer-critical characteristic\n- Easier/faster to implement\n\n**Key Lesson:** RPN is a prioritization tool, not the only decision criterion. Use engineering judgment.\n\n</details>\n\n### Application Questions\n\n<details>\n<summary>Question 7: For a metal stamping operation, identify at least five potential failure modes and their likely effects.</summary>\n\n**Metal Stamping PFMEA:**\n\n| # | Failure Mode | Effect |\n|---|--------------|--------|\n| 1 | Part not fully formed | Dimensional rejection, functional failure |\n| 2 | Burrs on edges | Injury hazard, assembly interference |\n| 3 | Cracks/splits | Structural failure, scrap |\n| 4 | Wrong material thickness | Dimensional/strength issues |\n| 5 | Mislocated features | Assembly issues, rejection |\n| 6 | Surface scratches | Appearance rejection, corrosion initiation |\n| 7 | Springback out of tolerance | Dimensional rejection |\n| 8 | Die mark/impression | Appearance defect |\n\n**Potential Causes for \"Part not fully formed\":**\n- Insufficient press tonnage\n- Die wear\n- Material too hard\n- Lubrication insufficient\n- Press speed too fast\n\n</details>\n\n<details>\n<summary>Question 8: A process has RPN of 240 (S=8, O=6, D=5). Propose three improvement strategies and calculate resulting RPN.</summary>\n\n**Current State:** S=8, O=6, D=5, RPN=240\n\n**Strategy 1: Improve Detection**\n- Add automated inspection (100% gauging)\n- New D = 2\n- New RPN = 8 × 6 × 2 = **96** (60% reduction)\n\n**Strategy 2: Improve Occurrence**\n- Add error-proofing (poka-yoke) to prevent cause\n- New O = 2\n- New RPN = 8 × 2 × 5 = **80** (67% reduction)\n\n**Strategy 3: Combined Approach**\n- Error-proofing (O → 3) + Better detection (D → 3)\n- New RPN = 8 × 3 × 3 = **72** (70% reduction)\n\n**Recommendation:** Strategy 2 (error-proofing) is typically preferred because:\n- Prevents defects from occurring\n- More sustainable long-term\n- Reduces inspection costs\n- Better for customer confidence\n\n</details>\n\n### Critical Thinking Questions\n\n<details>\n<summary>Question 9: Discuss the limitations of using RPN as the sole prioritization method.</summary>\n\n**RPN Limitations:**\n\n1. **Equal weighting problem:**\n   - 10×1×4 = 40 (safety hazard, rare)\n   - 2×10×2 = 40 (minor, frequent)\n   - Same RPN, very different risk!\n\n2. **Severity often overlooked:**\n   - High-severity items (9-10) should always be addressed\n   - RPN can hide safety-critical issues\n\n3. **Non-linear scales:**\n   - Difference between S=2 and S=3 is not same as S=8 and S=9\n   - Multiplication assumes linear relationship\n\n4. **Arbitrary thresholds:**\n   - Why is RPN=100 the \"action\" threshold?\n   - No scientific basis for specific cutoffs\n\n5. **Gaming the system:**\n   - Teams may manipulate ratings to avoid action\n   - Subjectivity in ratings\n\n**Better Approaches:**\n- Action Priority (AP) method\n- Always act on S ≥ 9 regardless of RPN\n- Consider multiple criteria (cost, feasibility, timing)\n- Use risk matrix visualization\n\n</details>\n\n<details>\n<summary>Question 10: How would you handle a situation where team members disagree on severity ratings?</summary>\n\n**Approach to Rating Disagreements:**\n\n**1. Clarify the failure effect:**\n- Ensure everyone understands the same effect\n- Be specific about which customer sees which impact\n\n**2. Reference the rating criteria:**\n- Use the standardized scale consistently\n- Point to specific criteria, not opinions\n\n**3. Consider worst-case scenario:**\n- PFMEA should consider worst reasonable case\n- \"Could this effect happen?\" vs \"Will it happen?\"\n\n**4. Gather data:**\n- Review historical data if available\n- What have similar failures caused in the past?\n\n**5. When in doubt, go higher:**\n- Conservative approach is appropriate for safety\n- Can always reduce later with evidence\n\n**6. Document the discussion:**\n- Record the rationale for the rating\n- Note if there was disagreement and why decision was made\n\n**7. Get external input:**\n- Bring in customer perspective if needed\n- Consult subject matter experts\n\n**Final Rule:** If a safety or regulatory issue is possible, severity should be 9 or 10 regardless of probability.\n\n</details>\n\n------------------------------------------------------------------------\n\n## References\n\n- AIAG & VDA. (2019). *FMEA Handbook*. Automotive Industry Action Group.\n- Stamatis, D.H. (2003). *Failure Mode and Effect Analysis: FMEA from Theory to Execution*. ASQ Quality Press.\n- McDermott, R.E., Mikulak, R.J., & Beauregard, M.R. (2009). *The Basics of FMEA*. Productivity Press.\n- Carlson, C.S. (2012). *Effective FMEAs: Achieving Safe, Reliable, and Economical Products and Processes*. Wiley.\n- SAE J1739. (2009). *Potential Failure Mode and Effects Analysis in Design and Manufacturing*.\n- ISO 31000:2018. *Risk management — Guidelines*.\n- IATF 16949:2016. *Quality management system requirements for automotive production*.\n\n------------------------------------------------------------------------\n",
    "supporting": [
      "14-PFMEA_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}