{
  "hash": "f8fe019545b73a92f6ea8378477027cf",
  "result": {
    "engine": "knitr",
    "markdown": "# Total Productive Maintenance (TPM)\n\n\n------------------------------------------------------------------------\n\n\n## Learning Objectives\n\nBy the end of this chapter, you will be able to:\n\n- Define Total Productive Maintenance and explain its objectives\n- Describe the 8 pillars of TPM and their interconnections\n- Calculate Overall Equipment Effectiveness (OEE) and its components\n- Identify and categorize the Six Big Losses\n- Implement autonomous maintenance activities\n- Develop preventive and predictive maintenance strategies\n- Apply TPM principles to improve equipment reliability and productivity\n\n> \"Take care of your equipment, and it will take care of your production.\"\n> — Seiichi Nakajima, Father of TPM\n\n------------------------------------------------------------------------\n\n## Introduction to TPM\n\n### What is Total Productive Maintenance?\n\n**Total Productive Maintenance (TPM)** is a holistic approach to equipment maintenance that strives to achieve perfect production with no breakdowns, no defects, and no accidents. It involves everyone in the organization, from operators to top management.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The TPM Philosophy](12-TPM_files/figure-pdf/tpm-definition-1.pdf){fig-align='center'}\n:::\n:::\n\n\n### History of TPM\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{8em}lll}\n\\caption{\\label{tab:tpm-history}Evolution of Maintenance Philosophy}\\\\\n\\toprule\n\\cellcolor[HTML]{34495E}{\\textcolor{white}{\\textbf{Era}}} & \\cellcolor[HTML]{34495E}{\\textcolor{white}{\\textbf{Maintenance Approach}}} & \\cellcolor[HTML]{34495E}{\\textcolor{white}{\\textbf{Description}}} & \\cellcolor[HTML]{34495E}{\\textcolor{white}{\\textbf{Key Change}}}\\\\\n\\midrule\n\\textbf{Pre-1950s} & Breakdown Maintenance & Fix it when it breaks; reactive only & No prevention\\\\\n\\textbf{1950s} & Preventive Maintenance & Scheduled maintenance to prevent failures & Time-based prevention\\\\\n\\textbf{1960s} & Productive Maintenance & Maintenance focused on reliability and maintainability & Design for maintenance\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{1970s}} & \\cellcolor[HTML]{D5F5E3}{TPM Developed} & \\cellcolor[HTML]{D5F5E3}{Nakajima develops TPM at Nippondenso (Toyota supplier)} & \\cellcolor[HTML]{D5F5E3}{Operator involvement}\\\\\n\\textbf{1980s} & TPM Spreads Globally & Adopted by automotive, electronics, process industries worldwide & World-class standard\\\\\n\\addlinespace\n\\textbf{1990s-Present} & TPM + Industry 4.0 & Integration with predictive analytics, IoT sensors, AI & Data-driven maintenance\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### The Goals of TPM\n\nTPM aims to achieve **zero** targets:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![TPM Zero Targets](12-TPM_files/figure-pdf/tpm-goals-1.pdf){fig-align='center'}\n:::\n:::\n\n\n### Traditional vs. TPM Approach\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{14em}>{}l>{}l}\n\\caption{\\label{tab:traditional-vs-tpm}Traditional Maintenance vs. TPM}\\\\\n\\toprule\n\\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Aspect}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Traditional Maintenance}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{TPM Approach}}}\\\\\n\\midrule\n\\textbf{**Equipment ownership**} & \\cellcolor[HTML]{FADBD8}{'Maintenance owns the machines'} & \\cellcolor[HTML]{D5F5E3}{'We all own the machines'}\\\\\n\\textbf{**Maintenance responsibility**} & \\cellcolor[HTML]{FADBD8}{Maintenance department only} & \\cellcolor[HTML]{D5F5E3}{Everyone (operators + maintenance)}\\\\\n\\textbf{**Operator role**} & \\cellcolor[HTML]{FADBD8}{Operate; call maintenance when broken} & \\cellcolor[HTML]{D5F5E3}{Operate, clean, inspect, maintain}\\\\\n\\textbf{**Maintenance focus**} & \\cellcolor[HTML]{FADBD8}{Fix breakdowns quickly} & \\cellcolor[HTML]{D5F5E3}{Prevent breakdowns; extend life}\\\\\n\\textbf{**Problem solving**} & \\cellcolor[HTML]{FADBD8}{Reactive; fire-fighting} & \\cellcolor[HTML]{D5F5E3}{Proactive; root cause elimination}\\\\\n\\addlinespace\n\\textbf{**Goal**} & \\cellcolor[HTML]{FADBD8}{Minimize maintenance cost} & \\cellcolor[HTML]{D5F5E3}{Maximize equipment effectiveness}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n<details>\n<summary>Question: Why involve operators in maintenance?</summary>\n\n**Operators are the first line of defense because:**\n\n1. **They know the equipment:** Operators work with machines every day and notice subtle changes\n2. **Early detection:** Small problems are detected before becoming major failures\n3. **Ownership mindset:** People take better care of things they \"own\"\n4. **Reduced response time:** Operators can address minor issues immediately\n5. **Freed maintenance resources:** Technicians can focus on complex tasks\n\n**Example:** An operator notices a slight vibration change in a motor. Under traditional maintenance, they might ignore it. Under TPM, they report it, potentially preventing a $50,000 breakdown.\n\n> \"No one knows a machine better than the person who operates it every day.\"\n\n</details>\n\n------------------------------------------------------------------------\n\n## The Eight Pillars of TPM\n\nTPM is built on **eight pillars**, each addressing a specific aspect of equipment management and organizational culture.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The Eight Pillars of TPM](12-TPM_files/figure-pdf/eight-pillars-1.pdf){fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{13}{15}\\selectfont\n\n\\begin{longtable}[t]{>{\\raggedleft\\arraybackslash}p{3em}lll}\n\\caption{\\label{tab:pillars-table}The Eight Pillars of TPM}\\\\\n\\toprule\n\\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{\\#}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{Pillar}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{Purpose}}} & \\cellcolor[HTML]{8E44AD}{\\textcolor{white}{\\textbf{Key Activities}}}\\\\\n\\midrule\n\\textbf{1} & **Autonomous Maintenance** & Operators maintain their own equipment & Cleaning, inspection, lubrication, minor repairs\\\\\n\\textbf{2} & **Planned Maintenance** & Scheduled maintenance by specialists & PM schedules, predictive maintenance, spare parts\\\\\n\\textbf{3} & **Quality Maintenance** & Zero defects through equipment conditions & Identify equipment conditions causing defects\\\\\n\\textbf{4} & **Focused Improvement** & Eliminate losses through kaizen activities & Loss analysis, root cause, countermeasures\\\\\n\\textbf{5} & **Early Equipment Management** & Design equipment for maintainability & Design reviews, vertical startup, LCC analysis\\\\\n\\addlinespace\n\\textbf{6} & **Training \\& Education** & Develop skilled operators and technicians & Skills matrix, training programs, OJT\\\\\n\\textbf{7} & **Safety, Health, Environment** & Zero accidents, safe workplace & Hazard identification, safety audits, ergonomics\\\\\n\\textbf{8} & **TPM in Office** & Apply TPM principles to administrative processes & Streamline workflows, reduce waste in offices\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Overall Equipment Effectiveness (OEE)\n\n### What is OEE?\n\n**Overall Equipment Effectiveness (OEE)** is the primary metric of TPM. It measures how effectively equipment is being used by combining three factors: Availability, Performance, and Quality.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![OEE Formula and Components](12-TPM_files/figure-pdf/oee-formula-1.pdf){fig-align='center'}\n:::\n:::\n\n\n### OEE Component Formulas\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{10em}lll}\n\\caption{\\label{tab:oee-formulas}OEE Component Formulas}\\\\\n\\toprule\n\\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{Component}}} & \\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{Formula}}} & \\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{What It Measures}}} & \\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{Losses Captured}}}\\\\\n\\midrule\n\\textbf{**Availability**} & \\$\\textbackslash{}frac\\{\\textbackslash{}text\\{Run Time\\}\\}\\{\\textbackslash{}text\\{Planned Production Time\\}\\} \\textbackslash{}times 100\\textbackslash{}\\%\\$ & Time the equipment is running vs. planned time & Breakdowns, changeovers, adjustments\\\\\n\\textbf{**Performance**} & \\$\\textbackslash{}frac\\{\\textbackslash{}text\\{Ideal Cycle Time\\} \\textbackslash{}times \\textbackslash{}text\\{Total Count\\}\\}\\{\\textbackslash{}text\\{Run Time\\}\\} \\textbackslash{}times 100\\textbackslash{}\\%\\$ & How fast equipment runs vs. design speed & Minor stops, reduced speed, idling\\\\\n\\textbf{**Quality**} & \\$\\textbackslash{}frac\\{\\textbackslash{}text\\{Good Count\\}\\}\\{\\textbackslash{}text\\{Total Count\\}\\} \\textbackslash{}times 100\\textbackslash{}\\%\\$ & Good parts vs. total parts produced & Defects, rework, startup rejects\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{**OEE**}} & \\cellcolor[HTML]{D5F5E3}{\\$\\textbackslash{}text\\{Availability\\} \\textbackslash{}times \\textbackslash{}text\\{Performance\\} \\textbackslash{}times \\textbackslash{}text\\{Quality\\}\\$} & \\cellcolor[HTML]{D5F5E3}{Overall effectiveness combining all three} & \\cellcolor[HTML]{D5F5E3}{All six big losses combined}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### OEE Calculation Example\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# OEE Calculation Example: Injection Molding Machine\n\ncat(\"=== SHIFT DATA ===\\n\")\n# Time data\nshift_length <- 480  # minutes (8 hours)\nplanned_downtime <- 30  # breaks, planned maintenance\nplanned_production_time <- shift_length - planned_downtime\ncat(\"Planned Production Time:\", planned_production_time, \"minutes\\n\")\n\n# Downtime losses\nbreakdown_time <- 25  # equipment failure\nchangeover_time <- 35  # mold changes\nadjustment_time <- 10  # setup adjustments\ntotal_downtime <- breakdown_time + changeover_time + adjustment_time\ncat(\"Unplanned Downtime:\", total_downtime, \"minutes\\n\")\n\nrun_time <- planned_production_time - total_downtime\ncat(\"Run Time:\", run_time, \"minutes\\n\\n\")\n\n# Production data\nideal_cycle_time <- 0.5  # minutes per part (design spec)\ntotal_parts <- 700  # parts produced\ngood_parts <- 665   # parts passing inspection\ndefects <- total_parts - good_parts\n\ncat(\"=== PRODUCTION DATA ===\\n\")\ncat(\"Total Parts Produced:\", total_parts, \"\\n\")\ncat(\"Good Parts:\", good_parts, \"\\n\")\ncat(\"Defects:\", defects, \"\\n\\n\")\n\n# Calculate OEE Components\ncat(\"=== OEE CALCULATION ===\\n\\n\")\n\n# Availability\navailability <- (run_time / planned_production_time) * 100\ncat(\"AVAILABILITY:\\n\")\ncat(\"  = Run Time / Planned Production Time\\n\")\ncat(\"  =\", run_time, \"/\", planned_production_time, \"\\n\")\ncat(\"  =\", round(availability, 1), \"%\\n\\n\")\n\n# Performance\n# Actual output vs. theoretical output during run time\ntheoretical_output <- run_time / ideal_cycle_time\nperformance <- (total_parts / theoretical_output) * 100\ncat(\"PERFORMANCE:\\n\")\ncat(\"  Theoretical Output =\", theoretical_output, \"parts\\n\")\ncat(\"  Actual Output =\", total_parts, \"parts\\n\")\ncat(\"  = Actual / Theoretical\\n\")\ncat(\"  =\", round(performance, 1), \"%\\n\\n\")\n\n# Quality\nquality <- (good_parts / total_parts) * 100\ncat(\"QUALITY:\\n\")\ncat(\"  = Good Parts / Total Parts\\n\")\ncat(\"  =\", good_parts, \"/\", total_parts, \"\\n\")\ncat(\"  =\", round(quality, 1), \"%\\n\\n\")\n\n# Overall OEE\noee <- (availability/100) * (performance/100) * (quality/100) * 100\ncat(\"=== OVERALL OEE ===\\n\")\ncat(\"OEE =\", round(availability, 1), \"% ×\", round(performance, 1), \"% ×\", round(quality, 1), \"%\\n\")\ncat(\"OEE =\", round(oee, 1), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== SHIFT DATA ===\nPlanned Production Time: 450 minutes\nUnplanned Downtime: 70 minutes\nRun Time: 380 minutes\n\n=== PRODUCTION DATA ===\nTotal Parts Produced: 700 \nGood Parts: 665 \nDefects: 35 \n\n=== OEE CALCULATION ===\n\nAVAILABILITY:\n  = Run Time / Planned Production Time\n  = 380 / 450 \n  = 84.4 %\n\nPERFORMANCE:\n  Theoretical Output = 760 parts\n  Actual Output = 700 parts\n  = Actual / Theoretical\n  = 92.1 %\n\nQUALITY:\n  = Good Parts / Total Parts\n  = 665 / 700 \n  = 95 %\n\n=== OVERALL OEE ===\nOEE = 84.4 % × 92.1 % × 95 %\nOEE = 73.9 %\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![OEE Waterfall Chart: Where Time Goes](12-TPM_files/figure-pdf/oee-waterfall-1.pdf){fig-align='center'}\n:::\n:::\n\n\n### OEE Benchmarks\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{8em}lll}\n\\caption{\\label{tab:oee-benchmarks}OEE Benchmarks}\\\\\n\\toprule\n\\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{OEE Level}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Classification}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Interpretation}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Component Targets}}}\\\\\n\\midrule\n\\textbf{\\cellcolor[HTML]{FADBD8}{< 65\\%}} & \\cellcolor[HTML]{FADBD8}{Unacceptable} & \\cellcolor[HTML]{FADBD8}{Significant improvement opportunities exist} & \\cellcolor[HTML]{FADBD8}{—}\\\\\n\\textbf{\\cellcolor[HTML]{FEF9E7}{65\\% - 75\\%}} & \\cellcolor[HTML]{FEF9E7}{Typical} & \\cellcolor[HTML]{FEF9E7}{Average for discrete manufacturing} & \\cellcolor[HTML]{FEF9E7}{A: 90\\%, P: 85\\%, Q: 95\\%}\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{75\\% - 85\\%}} & \\cellcolor[HTML]{D5F5E3}{Good} & \\cellcolor[HTML]{D5F5E3}{Well-managed operations} & \\cellcolor[HTML]{D5F5E3}{A: 92\\%, P: 90\\%, Q: 97\\%}\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{\\textbf{> 85\\%}}} & \\cellcolor[HTML]{D5F5E3}{\\textbf{World Class}} & \\cellcolor[HTML]{D5F5E3}{\\textbf{Best-in-class performance}} & \\cellcolor[HTML]{D5F5E3}{\\textbf{A: 95\\%, P: 95\\%, Q: 99\\%}}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n<details>\n<summary>Interactive Exercise: Calculate OEE</summary>\n\n**Given the following shift data, calculate OEE:**\n\n- Shift length: 480 minutes\n- Planned breaks: 40 minutes\n- Equipment breakdown: 30 minutes\n- Setup/changeover: 20 minutes\n- Ideal cycle time: 1 minute/part\n- Total parts produced: 350\n- Rejected parts: 14\n\n**Work through the calculation:**\n\n**Solution:**\n\n```\nPlanned Production Time = 480 - 40 = 440 minutes\nRun Time = 440 - 30 - 20 = 390 minutes\n\nAvailability = 390 / 440 = 88.6%\n\nTheoretical Output = 390 / 1 = 390 parts\nPerformance = 350 / 390 = 89.7%\n\nQuality = (350 - 14) / 350 = 336 / 350 = 96.0%\n\nOEE = 88.6% × 89.7% × 96.0% = 76.3%\n```\n\n**Interpretation:** This is \"Good\" performance, above the typical range. The biggest opportunity is in Performance (speed losses).\n\n</details>\n\n------------------------------------------------------------------------\n\n## The Six Big Losses\n\nTPM categorizes all equipment losses into **six categories**, which map directly to the OEE components.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The Six Big Losses](12-TPM_files/figure-pdf/six-big-losses-1.pdf){fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\\begingroup\\fontsize{13}{15}\\selectfont\n\n\\begin{longtable}[t]{>{\\raggedleft\\arraybackslash}p{3em}llll}\n\\caption{\\label{tab:six-losses-detail}The Six Big Losses Explained}\\\\\n\\toprule\n\\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{\\#}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{Loss Category}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{OEE Component}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{Description}}} & \\cellcolor[HTML]{E67E22}{\\textcolor{white}{\\textbf{Examples}}}\\\\\n\\midrule\n\\textbf{\\cellcolor[HTML]{D6EAF8}{1}} & \\cellcolor[HTML]{D6EAF8}{**Equipment Failure**} & \\cellcolor[HTML]{D6EAF8}{Availability} & \\cellcolor[HTML]{D6EAF8}{Unplanned equipment breakdown} & \\cellcolor[HTML]{D6EAF8}{Motor failure, sensor malfunction, mechanical breakdown}\\\\\n\\textbf{\\cellcolor[HTML]{D6EAF8}{2}} & \\cellcolor[HTML]{D6EAF8}{**Setup \\& Adjustment**} & \\cellcolor[HTML]{D6EAF8}{Availability} & \\cellcolor[HTML]{D6EAF8}{Time for changeover, tool changes, adjustments} & \\cellcolor[HTML]{D6EAF8}{Die change, product changeover, calibration}\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{3}} & \\cellcolor[HTML]{D5F5E3}{**Idling \\& Minor Stops**} & \\cellcolor[HTML]{D5F5E3}{Performance} & \\cellcolor[HTML]{D5F5E3}{Brief stoppages (jams, blockages, cleaning)} & \\cellcolor[HTML]{D5F5E3}{Sensor trips, material jams, overloads (<5 min)}\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{4}} & \\cellcolor[HTML]{D5F5E3}{**Reduced Speed**} & \\cellcolor[HTML]{D5F5E3}{Performance} & \\cellcolor[HTML]{D5F5E3}{Running slower than design speed} & \\cellcolor[HTML]{D5F5E3}{Worn tooling, operator caution, material variability}\\\\\n\\textbf{\\cellcolor[HTML]{FADBD8}{5}} & \\cellcolor[HTML]{FADBD8}{**Process Defects**} & \\cellcolor[HTML]{FADBD8}{Quality} & \\cellcolor[HTML]{FADBD8}{Defects produced during normal operation} & \\cellcolor[HTML]{FADBD8}{Scrap, rework, out-of-spec product}\\\\\n\\addlinespace\n\\textbf{\\cellcolor[HTML]{FADBD8}{6}} & \\cellcolor[HTML]{FADBD8}{**Startup Rejects**} & \\cellcolor[HTML]{FADBD8}{Quality} & \\cellcolor[HTML]{FADBD8}{Defects during warmup, startup, changeover} & \\cellcolor[HTML]{FADBD8}{First-off rejects, warming up, stabilization}\\\\\n\\bottomrule\n\\end{longtable}\n\\endgroup{}\n\n\n:::\n:::\n\n\n### Typical Loss Distribution\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Typical Distribution of the Six Big Losses](12-TPM_files/figure-pdf/loss-distribution-1.pdf){fig-align='center'}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Autonomous Maintenance\n\n**Autonomous Maintenance (AM)** is the first and most visible pillar of TPM. It transfers basic maintenance tasks from maintenance specialists to operators.\n\n### The Seven Steps of Autonomous Maintenance\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Seven Steps of Autonomous Maintenance](12-TPM_files/figure-pdf/am-seven-steps-1.pdf){fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedleft\\arraybackslash}p{4em}lll}\n\\caption{\\label{tab:am-steps-detail}Autonomous Maintenance Steps in Detail}\\\\\n\\toprule\n\\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Step}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Name}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Activities}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Outcome}}}\\\\\n\\midrule\n\\textbf{1} & **Initial Cleaning** & Deep clean equipment; identify abnormalities & Equipment baseline; 100+ abnormalities found typical\\\\\n\\textbf{2} & **Eliminate Contamination Sources** & Find and fix sources of dirt, leaks, contamination & Reduced cleaning time; contamination controlled\\\\\n\\textbf{3} & **Cleaning \\& Lubrication Standards** & Create standards for cleaning, lubricating, inspection & Consistent equipment condition; clear expectations\\\\\n\\textbf{4} & **General Inspection** & Train operators on equipment function; expand skills & Skilled operators; detect abnormalities early\\\\\n\\textbf{5} & **Autonomous Inspection** & Operators perform scheduled inspections independently & Reliable self-directed maintenance program\\\\\n\\addlinespace\n\\textbf{6} & **Organization \\& Tidiness** & Standardize workplace; visual management & Efficient, safe, visual workplace\\\\\n\\textbf{7} & **Full Autonomous Maintenance** & Continuous improvement; operators propose improvements & Empowered operators; sustained improvement\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### The AM Tag System\n\nDuring autonomous maintenance activities, operators identify abnormalities using **tags**:\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![AM Tag System](12-TPM_files/figure-pdf/tag-system-1.pdf){fig-align='center'}\n:::\n:::\n\n\n### Example: AM Cleaning and Inspection Checklist\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedleft\\arraybackslash}p{3em}llll}\n\\caption{\\label{tab:am-checklist}Sample AM Inspection Checklist}\\\\\n\\toprule\n\\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{\\#}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Check Item}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Method}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Standard}}} & \\cellcolor[HTML]{E74C3C}{\\textcolor{white}{\\textbf{Frequency}}}\\\\\n\\midrule\n\\textbf{1} & General cleanliness & Visual & No dust, debris, contamination & Daily\\\\\n\\textbf{2} & Oil/lubricant levels & Visual/gauge & Between min-max marks & Daily\\\\\n\\textbf{3} & Loose bolts/fasteners & Touch/wrench & Hand tight + 1/4 turn & Weekly\\\\\n\\textbf{4} & Unusual sounds & Listen & Normal operating sound & Each startup\\\\\n\\textbf{5} & Vibration & Touch & Minimal, no unusual patterns & Each startup\\\\\n\\addlinespace\n\\textbf{6} & Temperature & Touch/thermometer & < 60°C (or per spec) & Hourly\\\\\n\\textbf{7} & Leaks (oil, air, coolant) & Visual & No visible leaks & Daily\\\\\n\\textbf{8} & Safety guards in place & Visual & All guards secure & Each shift\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Planned Maintenance\n\n**Planned Maintenance** is the second pillar, focusing on scheduled maintenance activities performed by maintenance specialists.\n\n### Types of Maintenance\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Types of Maintenance Activities](12-TPM_files/figure-pdf/maintenance-types-1.pdf){fig-align='center'}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{10em}llll}\n\\caption{\\label{tab:maintenance-comparison}Maintenance Strategy Comparison}\\\\\n\\toprule\n\\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Type}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Approach}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Advantages}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Disadvantages}}} & \\cellcolor[HTML]{9B59B6}{\\textcolor{white}{\\textbf{Best For}}}\\\\\n\\midrule\n\\textbf{**Breakdown**} & Run to failure & No upfront cost & Unplanned downtime, secondary damage & Non-critical, cheap to replace\\\\\n\\textbf{**Preventive**} & Time/cycle-based replacement & Planned downtime, parts availability & May replace good parts & Wear items with known life\\\\\n\\textbf{**Predictive**} & Condition monitoring & Optimal component life, targeted actions & Monitoring investment required & Critical equipment, expensive failures\\\\\n\\textbf{**Proactive**} & Root cause elimination & Prevents future failures & Requires analysis capability & Recurring problems\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Predictive Maintenance Technologies\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}lll}\n\\caption{\\label{tab:pdm-technologies}Predictive Maintenance Technologies}\\\\\n\\toprule\n\\cellcolor[HTML]{3498DB}{\\textcolor{white}{\\textbf{Technology}}} & \\cellcolor[HTML]{3498DB}{\\textcolor{white}{\\textbf{What It Detects}}} & \\cellcolor[HTML]{3498DB}{\\textcolor{white}{\\textbf{Equipment Applications}}} & \\cellcolor[HTML]{3498DB}{\\textcolor{white}{\\textbf{Typical Warning Time}}}\\\\\n\\midrule\n\\textbf{**Vibration Analysis**} & Imbalance, misalignment, bearing wear, looseness & Rotating equipment (motors, pumps, fans, gearboxes) & Weeks to months\\\\\n\\textbf{**Thermography**} & Hot spots, electrical issues, friction, insulation problems & Electrical panels, motors, bearings, refractory & Hours to days\\\\\n\\textbf{**Oil Analysis**} & Contamination, wear particles, lubricant degradation & Gearboxes, hydraulics, engines, compressors & Weeks to months\\\\\n\\textbf{**Ultrasound**} & Leaks, bearing defects, electrical discharge & Steam traps, valves, bearings, electrical equipment & Days to weeks\\\\\n\\textbf{**Motor Current Analysis**} & Motor winding issues, rotor bar problems, power quality & Electric motors, drives, generators & Days to weeks\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### The P-F Curve\n\nThe **P-F Curve** illustrates the concept of detecting potential failure (P) before functional failure (F).\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![The P-F Curve: Detecting Failure Early](12-TPM_files/figure-pdf/pf-curve-1.pdf){fig-align='center'}\n:::\n:::\n\n\n<details>\n<summary>Question: Why is predictive maintenance better than preventive maintenance?</summary>\n\n**Preventive Maintenance (Time-Based):**\n- Replaces parts at fixed intervals regardless of condition\n- May replace parts still in good condition (waste)\n- May miss failures that occur before scheduled replacement\n- Based on average life, not individual component condition\n\n**Predictive Maintenance (Condition-Based):**\n- Monitors actual equipment condition\n- Replaces parts when condition indicates need\n- Maximizes component life\n- Provides warning time to plan repairs\n\n**Example:**\n- Preventive: Replace bearing every 6 months (may last 9 months or fail at 4 months)\n- Predictive: Monitor vibration; replace when trending indicates 2-3 weeks to failure\n- Result: Optimal component life, planned downtime, no unexpected failures\n\n**Cost Comparison:**\n- Reactive repair: $10,000 (including secondary damage, lost production)\n- Preventive replacement: $3,000 (may waste $1,000 in parts life)\n- Predictive replacement: $2,500 (optimal timing, minimal waste)\n\n</details>\n\n------------------------------------------------------------------------\n\n## Focused Improvement (Kobetsu Kaizen)\n\n**Focused Improvement** uses cross-functional teams to eliminate specific losses identified through OEE analysis.\n\n### The Kaizen Process\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Focused Improvement Process](12-TPM_files/figure-pdf/kaizen-process-1.pdf){fig-align='center'}\n:::\n:::\n\n\n#### Understanding Kaizen\n\n**Kaizen** (改善) is a Japanese term meaning \"change for better\" or **continuous improvement**. Unlike large-scale transformation projects, Kaizen focuses on small, incremental improvements made consistently over time. The philosophy is built on the belief that every process can be improved, and everyone—from operators to managers—should participate in identifying and implementing improvements.\n\n**Core Principles of Kaizen:**\n\n- **Good processes bring good results** — Focus on improving the process, not blaming people\n- **Go see for yourself (Gemba)** — Understand the actual situation at the workplace\n- **Speak with data** — Base decisions on facts and measurements\n- **Take action to contain and correct root causes** — Don't just treat symptoms\n- **Work as a team** — Cross-functional collaboration produces better solutions\n- **Kaizen is everybody's business** — Every employee can contribute improvements\n\n#### The Five Steps in Detail\n\n**Step 1: SELECT — Identify the Biggest Loss**\n\nThe first step uses data to identify which loss has the greatest impact on OEE. This typically involves:\n\n- Reviewing OEE data and breakdown logs\n- Creating Pareto charts to visualize loss magnitude\n- Selecting a loss that is significant, measurable, and within the team's ability to address\n- Forming a cross-functional team with members who understand the equipment and process\n\n*Key question: \"Which single problem, if solved, would give us the biggest improvement?\"*\n\n**Step 2: ANALYZE — Root Cause Analysis**\n\nOnce a loss is selected, the team investigates its root cause using structured problem-solving tools:\n\n- **Why-Why Analysis (5 Whys)**: Repeatedly asking \"why\" to drill down from symptoms to root causes\n- **Fishbone Diagram (Ishikawa)**: Categorizing potential causes by Machine, Method, Material, Man, Measurement, Environment\n- **PM Analysis**: A systematic method for chronic losses that examines physical mechanisms\n- **Data collection**: Gathering facts at the Gemba (actual workplace)\n\n*Key principle: Never assume you know the cause—verify with evidence.*\n\n**Step 3: DEVELOP — Create Countermeasures**\n\nBased on root cause analysis, the team develops countermeasures—actions designed to eliminate or reduce the root cause:\n\n- Brainstorm multiple potential solutions\n- Evaluate options based on effectiveness, cost, and implementation time\n- Create an action plan with clear responsibilities and deadlines\n- Consider both immediate fixes and permanent solutions\n- Apply error-proofing (Poka-Yoke) where possible\n\n*Important: Countermeasures address root causes, not just symptoms.*\n\n**Step 4: IMPLEMENT — Execute the Plan**\n\nThe team puts countermeasures into action:\n\n- Follow the action plan systematically\n- Make changes during planned downtime when possible\n- Document all modifications made\n- Train affected personnel on new procedures\n- Monitor results immediately after implementation\n- Be prepared to adjust if initial results are not as expected\n\n*Tip: Start with small-scale trials before full implementation when possible.*\n\n**Step 5: SUSTAIN — Standardize and Share**\n\nThe final step ensures improvements are maintained and shared across the organization:\n\n- **Standardize**: Update procedures, checklists, and work instructions to reflect the new method\n- **Visualize**: Create visual controls that make the standard easy to follow\n- **Train**: Ensure all shifts and new employees learn the improved method\n- **Verify**: Include checks in AM routines or audits to confirm the standard is being followed\n- **Share**: Communicate successful improvements to other areas that might benefit (Yokoten—horizontal deployment)\n\n*Kaizen is never finished—today's standard is tomorrow's baseline for further improvement.*\n\n#### Kaizen Event vs. Daily Kaizen\n\n| Aspect | Kaizen Event (Blitz) | Daily Kaizen |\n|--------|---------------------|--------------|\n| **Duration** | 3-5 days intensive | Ongoing, small improvements |\n| **Scope** | Focused on one specific problem | Any improvement opportunity |\n| **Team** | Dedicated cross-functional team | Individual or small group |\n| **Impact** | Significant, measurable improvement | Cumulative effect over time |\n| **Example** | Reduce changeover time by 50% | Reorganize tool storage for easier access |\n\nBoth approaches are valuable—Kaizen events tackle significant losses while daily Kaizen builds a culture of continuous improvement.\n\n### Loss Elimination Tools\n\nEffective loss elimination requires systematic tools that help teams identify problems, find root causes, and implement lasting solutions. The following tools are essential for Focused Improvement activities.\n\n#### Pareto Analysis\n\n**Pareto Analysis** applies the 80/20 rule: roughly 80% of losses come from 20% of causes. By creating a Pareto chart, teams can visualize which losses have the greatest impact and prioritize their improvement efforts accordingly.\n\n**How to use:**\n\n1. Collect data on all losses (downtime events, defects, speed reductions)\n2. Categorize losses by type or cause\n3. Calculate the frequency or duration of each category\n4. Rank categories from highest to lowest\n5. Create a bar chart with a cumulative percentage line\n6. Focus improvement efforts on the \"vital few\" categories that account for most losses\n\n#### Why-Why Analysis (5 Whys)\n\n**Why-Why Analysis** is a simple but powerful technique for drilling down from a symptom to its root cause by repeatedly asking \"Why?\" The goal is to go beyond surface-level explanations to find the fundamental cause that, if addressed, will prevent recurrence.\n\n**Example:**\n\n| Level | Question | Answer |\n|-------|----------|--------|\n| Problem | Machine stopped | Overload tripped |\n| Why 1? | Why did the overload trip? | Motor drew excessive current |\n| Why 2? | Why excessive current? | Bearing was seized |\n| Why 3? | Why was bearing seized? | Insufficient lubrication |\n| Why 4? | Why insufficient lubrication? | Lubrication schedule not followed |\n| Why 5? | Why not followed? | No visual indicator when lubrication is due |\n| **Root Cause** | | Missing visual management for lubrication schedule |\n\n**Tips for effective Why-Why Analysis:**\n\n- Stay focused on one causal chain at a time\n- Base answers on facts, not assumptions—verify at the Gemba\n- Don't stop at \"human error\"—ask why the error was possible\n- The number 5 is a guideline, not a rule—continue until you reach a controllable root cause\n\n#### PM Analysis\n\n**PM Analysis** (Physical Mechanism Analysis or Phenomenon-Mechanism Analysis) is a systematic method for analyzing **chronic losses**—problems that occur repeatedly despite multiple repair attempts. It examines the physical principles behind equipment failures.\n\n**The PM Analysis Process:**\n\n1. **Clarify the phenomenon**: Describe exactly what happens, when, and under what conditions\n2. **Conduct physical analysis**: Understand the physical principles involved (friction, heat, vibration, etc.)\n3. **Identify conditions that produce the phenomenon**: List all conditions required for the problem to occur\n4. **Investigate equipment, materials, and methods**: Examine each condition against the 4Ms (Machine, Material, Method, Man)\n5. **Plan and implement countermeasures**: Address the conditions that allow the problem to occur\n6. **Verify results**: Confirm the chronic loss has been eliminated\n\n*PM Analysis is particularly valuable when Why-Why Analysis doesn't resolve a recurring problem.*\n\n#### SMED (Single-Minute Exchange of Die)\n\n**SMED** is a systematic approach to reducing changeover or setup time—the time between the last good part of one product and the first good part of the next. The goal is to complete changeovers in under 10 minutes (single-digit minutes).\n\n**The SMED Process:**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![SMED Methodology](12-TPM_files/figure-pdf/smed-steps2-1.pdf){fig-align='center'}\n:::\n:::\n\n\n**Key Concepts:**\n\n- **Internal setup**: Tasks that can only be done when the machine is stopped (changing the die itself)\n- **External setup**: Tasks that can be done while the machine is running (preparing tools, preheating)\n\n**Typical SMED Improvements:**\n\n| Technique | Example |\n|-----------|---------|\n| Prepare in advance | Stage tools and materials before stopping the machine |\n| Use quick-release clamps | Replace bolts with cam locks or hydraulic clamps |\n| Eliminate adjustments | Use fixtures, stops, and standardized settings |\n| Parallel operations | Two people working simultaneously on different tasks |\n| Standardize components | Use common bolt sizes, connection types |\n\n#### Poka-Yoke (Error-Proofing)\n\n**Poka-Yoke** (ポカヨケ) means \"mistake-proofing\" or \"error-proofing.\" These are devices or methods that either prevent errors from occurring or detect them immediately when they do occur.\n\n**Types of Poka-Yoke:**\n\n| Type | Function | Example |\n|------|----------|---------|\n| **Prevention** | Makes errors impossible | Asymmetric connector that only fits one way |\n| **Detection** | Identifies errors immediately | Sensor that stops the line if a part is missing |\n| **Warning** | Alerts operator to potential error | Light or buzzer when a step is skipped |\n\n**Poka-Yoke Design Principles:**\n\n1. **Design out the possibility of error** — The best Poka-Yoke makes the error impossible\n2. **Detect at the source** — Catch errors where they occur, not downstream\n3. **Stop and fix immediately** — Don't pass defects to the next process\n4. **Keep it simple** — Low-cost, reliable solutions are better than complex ones\n\n**Examples in Manufacturing:**\n\n- **Guide pins** that prevent a part from being loaded incorrectly\n- **Counters** that verify the correct number of components were installed\n- **Checklists with physical verification** (e.g., removing a flag for each completed step)\n- **Limit switches** that confirm proper positioning before the cycle starts\n- **Color coding** to match parts with their correct locations\n\n<details>\n<summary>Question: How do you decide which tool to use?</summary>\n\n**Tool Selection Guide:**\n\n- **Pareto Analysis**: Use first to identify which loss to focus on\n- **Why-Why Analysis**: Use for sporadic failures with clear cause-effect relationships\n- **PM Analysis**: Use for chronic losses that keep recurring despite repairs\n- **SMED**: Use specifically for setup/changeover losses (Loss #2)\n- **Poka-Yoke**: Use to prevent defects and human errors (Losses #5, #6)\n\nOften, multiple tools are used together—Pareto to select the problem, Why-Why or PM Analysis to find the root cause, and Poka-Yoke to prevent recurrence.\n\n</details>\n\n#### Summary of Loss Elimination Tools\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}ll}\n\\caption{\\label{tab:loss-tools}Tools for Loss Elimination}\\\\\n\\toprule\n\\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Tool}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Purpose}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Application}}}\\\\\n\\midrule\n\\textbf{**Pareto Analysis**} & Identify biggest losses to target & Prioritize improvement efforts\\\\\n\\textbf{**Why-Why Analysis**} & Find root cause of failures & Breakdown analysis, defect investigation\\\\\n\\textbf{**PM Analysis**} & Analyze chronic losses systematically & Complex, recurring problems\\\\\n\\textbf{**SMED**} & Reduce setup/changeover time & Availability improvement (Loss \\#2)\\\\\n\\textbf{**Poka-Yoke**} & Error-proof the process & Quality improvement (Losses \\#5, \\#6)\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## TPM Implementation\n\n### The 12 Steps of TPM Implementation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{10em}rll}\n\\caption{\\label{tab:implementation-steps-TPM}12 Steps of TPM Implementation}\\\\\n\\toprule\n\\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{Phase}}} & \\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{Step}}} & \\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{Activity}}} & \\cellcolor[HTML]{16A085}{\\textcolor{white}{\\textbf{Duration}}}\\\\\n\\midrule\n\\textbf{\\cellcolor[HTML]{D6EAF8}{**Preparation**}} & \\cellcolor[HTML]{D6EAF8}{1} & \\cellcolor[HTML]{D6EAF8}{Announce TPM introduction by top management} & \\cellcolor[HTML]{D6EAF8}{1 month}\\\\\n\\textbf{\\cellcolor[HTML]{D6EAF8}{**Preparation**}} & \\cellcolor[HTML]{D6EAF8}{2} & \\cellcolor[HTML]{D6EAF8}{Education and campaign to introduce TPM} & \\cellcolor[HTML]{D6EAF8}{3-6 months}\\\\\n\\textbf{\\cellcolor[HTML]{D6EAF8}{**Preparation**}} & \\cellcolor[HTML]{D6EAF8}{3} & \\cellcolor[HTML]{D6EAF8}{Create TPM promotion organization} & \\cellcolor[HTML]{D6EAF8}{1-2 months}\\\\\n\\textbf{\\cellcolor[HTML]{D6EAF8}{**Preparation**}} & \\cellcolor[HTML]{D6EAF8}{4} & \\cellcolor[HTML]{D6EAF8}{Establish basic TPM policies and goals} & \\cellcolor[HTML]{D6EAF8}{1-2 months}\\\\\n\\textbf{\\cellcolor[HTML]{D6EAF8}{**Preparation**}} & \\cellcolor[HTML]{D6EAF8}{5} & \\cellcolor[HTML]{D6EAF8}{Formulate master plan for TPM development} & \\cellcolor[HTML]{D6EAF8}{1-2 months}\\\\\n\\addlinespace\n\\textbf{\\cellcolor[HTML]{D5F5E3}{**Implementation**}} & \\cellcolor[HTML]{D5F5E3}{6} & \\cellcolor[HTML]{D5F5E3}{Hold TPM kick-off} & \\cellcolor[HTML]{D5F5E3}{1 day}\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{**Implementation**}} & \\cellcolor[HTML]{D5F5E3}{7} & \\cellcolor[HTML]{D5F5E3}{Improve effectiveness of each piece of equipment} & \\cellcolor[HTML]{D5F5E3}{6-12 months}\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{**Implementation**}} & \\cellcolor[HTML]{D5F5E3}{8} & \\cellcolor[HTML]{D5F5E3}{Develop autonomous maintenance program} & \\cellcolor[HTML]{D5F5E3}{12-24 months}\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{**Implementation**}} & \\cellcolor[HTML]{D5F5E3}{9} & \\cellcolor[HTML]{D5F5E3}{Develop planned maintenance program} & \\cellcolor[HTML]{D5F5E3}{12-24 months}\\\\\n\\textbf{\\cellcolor[HTML]{D5F5E3}{**Implementation**}} & \\cellcolor[HTML]{D5F5E3}{10} & \\cellcolor[HTML]{D5F5E3}{Conduct training to improve skills} & \\cellcolor[HTML]{D5F5E3}{Ongoing}\\\\\n\\addlinespace\n\\textbf{\\cellcolor[HTML]{FCE4D6}{**Stabilization**}} & \\cellcolor[HTML]{FCE4D6}{11} & \\cellcolor[HTML]{FCE4D6}{Develop early equipment management program} & \\cellcolor[HTML]{FCE4D6}{12-24 months}\\\\\n\\textbf{\\cellcolor[HTML]{FCE4D6}{**Stabilization**}} & \\cellcolor[HTML]{FCE4D6}{12} & \\cellcolor[HTML]{FCE4D6}{Perfect TPM implementation and raise levels} & \\cellcolor[HTML]{FCE4D6}{Ongoing}\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n### Success Factors\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{15em}l}\n\\caption{\\label{tab:success-factors}TPM Success Factors}\\\\\n\\toprule\n\\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Factor}}} & \\cellcolor[HTML]{27AE60}{\\textcolor{white}{\\textbf{Why Critical}}}\\\\\n\\midrule\n\\textbf{**Top Management Commitment**} & Resources, culture change, sustained focus\\\\\n\\textbf{**Training and Education**} & Skills to identify problems, perform maintenance\\\\\n\\textbf{**Small Group Activities**} & Operator involvement, team problem-solving\\\\\n\\textbf{**Visual Management**} & Make abnormalities obvious, track progress\\\\\n\\textbf{**Patience and Persistence**} & TPM takes 3-5 years to fully implement\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Case Study: TPM Implementation\n\n### Background\n\n**Company:** Automotive component manufacturer\n\n**Equipment:** CNC machining center\n\n**Initial OEE:** 52%\n\n### Problem Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Initial State\ncat(\"=== INITIAL OEE BREAKDOWN ===\\n\\n\")\n\navailability_initial <- 78  # %\nperformance_initial <- 82   # %\nquality_initial <- 81       # %\n\noee_initial <- (availability_initial/100) * (performance_initial/100) * (quality_initial/100) * 100\ncat(\"Availability:\", availability_initial, \"%\\n\")\ncat(\"Performance:\", performance_initial, \"%\\n\")\ncat(\"Quality:\", quality_initial, \"%\\n\")\ncat(\"OEE:\", round(oee_initial, 1), \"%\\n\\n\")\n\n# Loss breakdown\ncat(\"=== TOP LOSSES IDENTIFIED ===\\n\")\ncat(\"1. Equipment breakdowns: 8% of time\\n\")\ncat(\"2. Setup/changeover: 7% of time\\n\")\ncat(\"3. Minor stops: 12% of time\\n\")\ncat(\"4. Defects: 4% of production\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== INITIAL OEE BREAKDOWN ===\n\nAvailability: 78 %\nPerformance: 82 %\nQuality: 81 %\nOEE: 51.8 %\n\n=== TOP LOSSES IDENTIFIED ===\n1. Equipment breakdowns: 8% of time\n2. Setup/changeover: 7% of time\n3. Minor stops: 12% of time\n4. Defects: 4% of production\n```\n\n\n:::\n:::\n\n\n### Improvements Implemented\n\n| Loss | Root Cause | Countermeasure | Result |\n|------|------------|----------------|--------|\n| Breakdowns | Lack of basic maintenance | Autonomous maintenance program | 8% → 3% |\n| Setup time | No standard procedure | SMED implementation | 35 min → 12 min |\n| Minor stops | Chip buildup in sensors | Improved chip management | 12% → 4% |\n| Defects | Tool wear not detected | In-process gauging | 4% → 1.5% |\n\n### Results After 18 Months\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# After TPM Implementation\ncat(\"=== FINAL OEE BREAKDOWN ===\\n\\n\")\n\navailability_final <- 91    # %\nperformance_final <- 94     # %\nquality_final <- 98.5       # %\n\noee_final <- (availability_final/100) * (performance_final/100) * (quality_final/100) * 100\ncat(\"Availability:\", availability_final, \"% (was\", availability_initial, \"%)\\n\")\ncat(\"Performance:\", performance_final, \"% (was\", performance_initial, \"%)\\n\")\ncat(\"Quality:\", quality_final, \"% (was\", quality_initial, \"%)\\n\")\ncat(\"OEE:\", round(oee_final, 1), \"% (was\", round(oee_initial, 1), \"%)\\n\\n\")\n\nimprovement <- oee_final - oee_initial\ncat(\"=== IMPROVEMENT ===\\n\")\ncat(\"OEE Improvement:\", round(improvement, 1), \"percentage points\\n\")\ncat(\"Relative Improvement:\", round((improvement/oee_initial)*100, 0), \"%\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n=== FINAL OEE BREAKDOWN ===\n\nAvailability: 91 % (was 78 %)\nPerformance: 94 % (was 82 %)\nQuality: 98.5 % (was 81 %)\nOEE: 84.3 % (was 51.8 %)\n\n=== IMPROVEMENT ===\nOEE Improvement: 32.4 percentage points\nRelative Improvement: 63 %\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![OEE Improvement: Before and After TPM](12-TPM_files/figure-pdf/case-visualization-1.pdf){fig-align='center'}\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Summary\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{12em}l}\n\\caption{\\label{tab:summary-table-ch10}TPM Key Concepts Summary}\\\\\n\\toprule\n\\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Topic}}} & \\cellcolor[HTML]{2C3E50}{\\textcolor{white}{\\textbf{Key Points}}}\\\\\n\\midrule\n**TPM Definition** & Total involvement, productive focus, maintenance excellence; zero breakdowns/defects/accidents\\\\\n**Eight Pillars** & AM, PM, Quality, Focused Improvement, Early Equipment, Training, Safety, Office — built on 5S\\\\\n**OEE** & OEE = Availability × Performance × Quality; World class > 85\\%\\\\\n**Six Big Losses** & Equipment failure, setup, minor stops, speed loss, defects, startup rejects\\\\\n**Autonomous Maintenance** & Operators maintain own equipment; 7 steps from cleaning to full ownership\\\\\n\\addlinespace\n**Planned Maintenance** & Preventive → Predictive → Proactive; use P-F curve for optimal timing\\\\\n\\bottomrule\n\\end{longtable}\n\n\n:::\n:::\n\n\n------------------------------------------------------------------------\n\n## Review Questions\n\n### Conceptual Questions\n\n<details>\n<summary>Question 1: What does \"Total\" mean in Total Productive Maintenance?</summary>\n\n**\"Total\" has three dimensions:**\n\n1. **Total participation:** Everyone participates, from operators to top management\n2. **Total equipment effectiveness:** Aim for maximum OEE (zero losses)\n3. **Total system:** Covers the entire equipment lifecycle, from design to disposal\n\n**Key insight:** TPM is not just a maintenance program — it's a company-wide philosophy where everyone takes responsibility for equipment care.\n\n</details>\n\n<details>\n<summary>Question 2: Why is OEE calculated as a product rather than a sum?</summary>\n\n**OEE uses multiplication because losses are sequential and compound:**\n\n1. **Availability** determines how much time is available\n2. **Performance** determines how much of that time is productive\n3. **Quality** determines how much of that production is good\n\n**Example:**\n- If each factor is 90%: OEE = 0.9 × 0.9 × 0.9 = 72.9% (not 270% or 90%)\n- This reflects reality: you can only achieve quality on parts that were produced (performance) during time the machine ran (availability)\n\n**Why this matters:**\n- Small improvements in all three factors compound\n- 5% improvement in each: 0.85 × 0.85 × 0.85 = 61% → 0.90 × 0.90 × 0.90 = 73%\n- Focus on the weakest factor first for biggest impact\n\n</details>\n\n<details>\n<summary>Question 3: What is the difference between autonomous maintenance and planned maintenance?</summary>\n\n| Aspect | Autonomous Maintenance | Planned Maintenance |\n|--------|------------------------|---------------------|\n| **Who** | Operators | Maintenance technicians |\n| **What** | Basic care (clean, inspect, lubricate) | Complex repairs, overhauls |\n| **When** | Daily, during operation | Scheduled intervals |\n| **Skills** | Basic equipment knowledge | Technical expertise |\n| **Goal** | Prevent deterioration | Restore/improve equipment |\n\n**They complement each other:**\n- AM catches problems early (first line of defense)\n- PM provides specialized skills when needed\n- Together they achieve zero breakdowns\n\n</details>\n\n### Calculation Questions\n\n<details>\n<summary>Question 4: Calculate OEE given the following data.</summary>\n\n**Given:**\n- Shift length: 480 minutes\n- Breaks: 30 minutes\n- Changeover: 45 minutes\n- Breakdown: 20 minutes\n- Ideal cycle time: 30 seconds (0.5 min)\n- Total parts produced: 580\n- Rejected parts: 23\n\n**Solution:**\n\n```\nPlanned Production Time = 480 - 30 = 450 minutes\nRun Time = 450 - 45 - 20 = 385 minutes\n\nAvailability = 385 / 450 = 85.6%\n\nTheoretical Output = 385 / 0.5 = 770 parts\nPerformance = 580 / 770 = 75.3%\n\nQuality = (580 - 23) / 580 = 557 / 580 = 96.0%\n\nOEE = 85.6% × 75.3% × 96.0% = 61.9%\n```\n\n**Analysis:** Performance is the biggest opportunity for improvement (75.3% vs. targets of 95%). Investigate minor stops and speed losses.\n\n</details>\n\n<details>\n<summary>Question 5: A machine has OEE of 65% with Availability 90%, Performance 80%, Quality 90%. Which factor should be prioritized?</summary>\n\n**Analysis:**\n\nCurrent state:\n- Availability: 90% (Gap to world class: 5%)\n- Performance: 80% (Gap to world class: 15%)\n- Quality: 90% (Gap to world class: 9%)\n\n**Performance should be prioritized because:**\n\n1. **Biggest gap:** 15 percentage points below world class (95%)\n2. **Biggest OEE impact:** Improving performance 10% → OEE = 90% × 90% × 90% = 72.9%\n3. **Often overlooked:** Speed losses and minor stops are frequently accepted as normal\n\n**Investigation areas for performance:**\n- Minor stops (jams, blockages, sensor trips)\n- Reduced speed operation\n- Idling and waiting\n- Operator pace\n\n</details>\n\n<details>\n<summary>Question 6: If current OEE is 60% and target is 85%, what improvement is needed in each component assuming equal improvement?</summary>\n\n**Solution:**\n\nCurrent: 60% = A × P × Q\n\nIf we improve each equally, we need:\n- Target: 85% = A' × P' × Q'\n- If A' = P' = Q' = x, then x³ = 0.85\n- x = ∛0.85 = 0.947 = 94.7%\n\n**Each component needs to reach approximately 95%**\n\n**Check:** 0.947 × 0.947 × 0.947 = 0.849 ≈ 85%\n\n**If current factors are A=80%, P=85%, Q=88%:**\n- Availability needs: +15 points (80% → 95%)\n- Performance needs: +10 points (85% → 95%)\n- Quality needs: +7 points (88% → 95%)\n\n**Prioritize by gap size:** Availability first, then Performance, then Quality.\n\n</details>\n\n### Application Questions\n\n<details>\n<summary>Question 7: An operator notices a small oil leak on a machine. Under traditional maintenance vs. TPM, what happens?</summary>\n\n**Traditional Maintenance Approach:**\n1. Operator continues running machine\n2. May or may not report to maintenance\n3. If reported, added to backlog\n4. Maintenance addresses when convenient (days/weeks)\n5. Leak worsens, potential bearing damage\n6. Eventually leads to breakdown\n\n**TPM Approach:**\n1. Operator notices during routine inspection\n2. Tags the abnormality immediately\n3. Determines if operator can fix (blue tag) or needs maintenance (red tag)\n4. If simple: operator tightens fitting or adds sealant\n5. If complex: maintenance prioritizes based on severity\n6. Root cause investigated to prevent recurrence\n7. Finding shared in team meeting\n\n**Key Differences:**\n- **Ownership:** Operator takes responsibility vs. \"not my job\"\n- **Speed:** Immediate action vs. delayed response\n- **Prevention:** Fixed before failure vs. reactive repair\n- **Cost:** $10 seal vs. $5,000 bearing replacement + downtime\n\n</details>\n\n<details>\n<summary>Question 8: List five items an operator should check during daily autonomous maintenance.</summary>\n\n**Five Essential Daily AM Checks:**\n\n1. **Cleanliness:** Remove chips, debris, dust; clean safety windows and sensors\n   - *Why:* Contamination causes wear, sensor malfunctions, quality issues\n\n2. **Lubrication:** Check oil levels, grease points, coolant level\n   - *Why:* Inadequate lubrication causes friction, heat, accelerated wear\n\n3. **Fasteners:** Check for loose bolts, guards, covers\n   - *Why:* Loose fasteners cause vibration, safety hazards, misalignment\n\n4. **Leaks:** Look for oil, coolant, air, hydraulic leaks\n   - *Why:* Leaks indicate seal failure, waste resources, create hazards\n\n5. **Abnormal sounds/vibration:** Listen and feel during startup\n   - *Why:* Changes indicate developing problems (bearings, alignment)\n\n**Bonus items:**\n- Safety guards in place\n- Emergency stops functional\n- Pressure/temperature gauges in normal range\n- No unusual smells (burning, chemical)\n\n</details>\n\n<details>\n<summary>Question 9: Explain how SMED relates to OEE improvement.</summary>\n\n**SMED (Single Minute Exchange of Die) directly improves Availability:**\n\n**Loss #2: Setup and Adjustment** is an availability loss captured in OEE.\n\n**How SMED helps:**\n\n1. **Reduces changeover time:**\n   - Before SMED: 45-minute changeover\n   - After SMED: 10-minute changeover\n   - Gain: 35 minutes per changeover\n\n2. **Impact on OEE:**\n   - If 2 changeovers per shift: 70 minutes saved\n   - On 450-minute shift: Availability improves 15%+\n\n3. **Secondary benefits:**\n   - More changeovers become practical\n   - Smaller batch sizes possible\n   - Flexibility increased\n   - Less WIP inventory\n\n**SMED Process:**\n1. Separate internal (machine stopped) from external (while running) setup\n2. Convert internal to external where possible\n3. Streamline remaining internal operations\n4. Practice and standardize\n\n**Example:** Die change on press\n- External: Stage next die, prepare tools, preheat\n- Internal: Remove old die, install new die, adjust\n- Target: All possible work done while machine runs\n\n</details>\n\n------------------------------------------------------------------------\n\n## References\n\n- Nakajima, S. (1988). *Introduction to TPM: Total Productive Maintenance*. Productivity Press.\n- Nakajima, S. (1989). *TPM Development Program: Implementing Total Productive Maintenance*. Productivity Press.\n- Shirose, K. (1992). *TPM for Operators*. Productivity Press.\n- Willmott, P., & McCarthy, D. (2001). *TPM: A Route to World-Class Performance*. Butterworth-Heinemann.\n- JIPM (Japan Institute of Plant Maintenance). *TPM Awards Criteria*.\n- Hansen, R.C. (2001). *Overall Equipment Effectiveness*. Industrial Press.\n- Borris, S. (2006). *Total Productive Maintenance*. McGraw-Hill.\n\n------------------------------------------------------------------------\n",
    "supporting": [
      "12-TPM_files\\figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabularx\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xltabular\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}